### DISCUSSION TITLE
Running Langfuse in Kubernetes

### DISCUSSION THREAD

**Discussion by mikeon** [langfuse/langfuse#1417] [Support] [answered]
Hi guys, did you manage to run langfuse in Kubernetes? Would it be possible to share configs?

I have currently a problem, so that Langfuse is using Nextjs and it is configured to use certain paths for assets. I don't know how to change that. 
![image](https://github.com/langfuse/langfuse/assets/5015029/15665d15-0552-4e14-a95f-f93d5804168f)

My part of deployments config:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
        - name: langfuse
          image: ghcr.io/langfuse/langfuse:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "postgresql://admin:admin@postgres:5432/vectordb"
            - name: NEXTAUTH_URL
              value: "http://langfuse:3000"
            - name: NEXTAUTH_SECRET
              value: "mysecret"
            - name: SALT
              value: "mysalt"
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse
spec:
  selector:
    app: langfuse
  ports:
    - port: 3000
      targetPort: 3000
```

and part of the Ingress config:

```
spec:
  ingressClassName: nginx # or another appropriate class name
  rules:
    - http:
        paths:
          - path: /bot
            pathType: Prefix
            backend: 
              service:
                name: bot
                port:
                  number: 8080
          - path: /langfuse
            pathType: Prefix
            backend: 
              service:
                name: langfuse
                port:
                  number: 3000
```
