### DISCUSSION TITLE
Langfuse images for arm64 (mac silicon, some cloud vms)

### DISCUSSION THREAD

**Discussion by verdverm** [langfuse/langfuse#1460] [Ideas]
### Describe the feature or potential improvement

It seems the only published images are for `linux/amd`?

I'm seeing the following from `docker compose`

```
! langfuse The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
```

Though it still _works_ because I setup colima & emulation iirc

### Additional information

Probably need to setup `docker-buildx` action with the `platforms` value set

I have an example here: https://github.com/hofstadter-io/hof/blob/_dev/.github/workflows/fmt.yml#L45

`docker-compose.yml` snippet:

```yaml
  langfuse:
    container_name: langfuse
    image: ghcr.io/langfuse/langfuse:2.11.3
    depends_on:
      - lf-psql
    networks:
      - ts-dev
    ports:
      - "0.0.0.0:3001:3001"
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3001
      - DATABASE_URL=postgresql://lf:lf@lf-psql:5433/lf?schema=public
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3001
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
```
