### DISCUSSION TITLE
502-Bad Request

### DISCUSSION THREAD

**Discussion by tbarbito** [langfuse/langfuse#1481] [Support] [answered]
### Describe the bug

When accessing my lagfuse the error occurs: _502-Bad Request_
I'm using the latest version of lagfuse on docker.
I attach my yaml file for analysis.
[langfuse_rm.zip](https://github.com/langfuse/langfuse/files/14722854/langfuse_rm.zip)

Thank you very much.

### To reproduce

When accessing the URL of my langfuse the error occurs on the browser screen:

![image](https://github.com/langfuse/langfuse/assets/163202065/24ebecf6-aea1-497a-9a31-3d5372d8476e)

### Additional information

My docker version is:
Client: Docker Engine - Community
 Version: 26.0.0
 API version: 1.45
 Go version: go1.21.8
 Git commit: 2ae903e
 Built: Wed Mar 20 15:18:01 2024
 OS/Arch: linux/amd64
 Context: default

Server: Docker Engine - Community
 Engine:
  Version: 26.0.0
  API version: 1.45 (minimum version 1.24)
  Go version: go1.21.8
  Git commit: 8b79278
  Built: Wed Mar 20 15:18:01 2024
  OS/Arch: linux/amd64
  Experimental: false
 containerd:
  Version: 1.6.28
  GitCommit: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version: 1.1.12
  GitCommit: v1.1.12-0-g51d5e94
 docker-init:
  Version: 0.19.0
  GitCommit: de40ad0

**Comment by maxdeichmann** [comment, marked as answer]
Hi @tbarbito thanks for reporting this. This is not a bug, as the current docker container works as expected. This likely is an issue with the configuration of your deployment.

**Comment by FrostScent** [comment]
Just set `HOSTNAME` to `0.0.0.0`.

I had the same problem.
My environment is Docker Swarm cluster, traefik proxy. 
service and proxy has no problem, and i got `bad gateway` too.

I solved this problem with this [trouble shooting guide](https://langfuse.com/docs/deployment/self-host#troubleshooting)

**Comment by daviddwlee84** [comment]
Tried to set `HOSTNAME` to `0.0.0.0` but still get 502 error

```
Bad gateway. This is an unusual occurrence and we are monitoring it closely. For help, please contact support: https://langfuse.com/support.
Traceback (most recent call last):
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langfuse\api\resources\projects\client.py", line 65, in get
    _response_json = _response.json()
                     ^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\httpx\_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\david\Documents\Program\LangfusePlayground\quick_test.py", line 16, in <module>
    print(langfuse.auth_check())
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langfuse\client.py", line 412, in auth_check
    raise e
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langfuse\client.py", line 400, in auth_check
    projects = self.client.projects.get()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\david\AppData\Roaming\Python\Python311\site-packages\langfuse\api\resources\projects\client.py", line 67, in get
    raise ApiError(status_code=_response.status_code, body=_response.text)
langfuse.api.core.api_error.ApiError: status_code: 502, body:
```

Here is the docker compose configure

```yaml
# https://github.com/langfuse/langfuse/blob/main/docker-compose.yml
services:
  reverse-proxy:
    image: traefik:v3.1.2
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      # - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
    ports:
      # The HTTP port
      - "${SERVER_PORT:-8089}:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      # https://langfuse.com/docs/deployment/self-host#troubleshooting
      # https://github.com/orgs/langfuse/discussions/1481
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://${SERVER_HOST:-localhost}:${SERVER_PORT:-8089}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_INIT_ORG_ID=${LANGFUSE_INIT_ORG_ID:-}
      - LANGFUSE_INIT_ORG_NAME=${LANGFUSE_INIT_ORG_NAME:-}
      - LANGFUSE_INIT_PROJECT_ID=${LANGFUSE_INIT_PROJECT_ID:-}
      - LANGFUSE_INIT_PROJECT_NAME=${LANGFUSE_INIT_PROJECT_NAME:-}
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}
      - LANGFUSE_INIT_USER_EMAIL=${LANGFUSE_INIT_USER_EMAIL:-}
      - LANGFUSE_INIT_USER_NAME=${LANGFUSE_INIT_USER_NAME:-}
      - LANGFUSE_INIT_USER_PASSWORD=${LANGFUSE_INIT_USER_PASSWORD:-}
    # https://langfuse.com/docs/deployment/self-host#custom-base-path
    labels:
      traefik.http.routers.langfuse.rule: "Host(`${SERVER_HOST:-localhost}`)"
      traefik.http.services.langfuse.loadbalancer.server.port: 3000

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

This is the environment configure

```ini
# Docker Compose
SERVER_HOST=localhost
SERVER_PORT=8089
# Langfuse
# TELEMETRY_ENABLED=true
# LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
LANGFUSE_INIT_ORG_ID=0
LANGFUSE_INIT_ORG_NAME=Puff
LANGFUSE_INIT_PROJECT_ID=0
LANGFUSE_INIT_PROJECT_NAME=Puff
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=public_key
LANGFUSE_INIT_PROJECT_SECRET_KEY=secret_key
LANGFUSE_INIT_USER_EMAIL=admin@email.com
LANGFUSE_INIT_USER_NAME=Admin
# Password needs to be at least 8 characters long
LANGFUSE_INIT_USER_PASSWORD=password

# Streamlit (Just follow the settings above or can be customized in Langfuse)
LANGFUSE_HOST="http://localhost:8089"
LANGFUSE_PUBLIC_KEY=public_key
LANGFUSE_SECRET_KEY=secret_key
```

And here is the Python code

```python
from langfuse import Langfuse
from dotenv import load_dotenv
import os

load_dotenv()

# LANGFUSE_HOST = f"http://{os.getenv('SERVER_HOST')}:{os.getenv('SERVER_PORT')}"
LANGFUSE_HOST = "http://localhost:3000"
PUBLIC_KEY = os.getenv("LANGFUSE_INIT_PROJECT_PUBLIC_KEY")
SECRET_KEY = os.getenv("LANGFUSE_INIT_PROJECT_SECRET_KEY")
print(LANGFUSE_HOST, PUBLIC_KEY, SECRET_KEY)

# https://langfuse.com/docs/sdk/python/decorators
langfuse = Langfuse(secret_key=SECRET_KEY, public_key=PUBLIC_KEY, host=LANGFUSE_HOST)

print(langfuse.auth_check())

from langfuse.decorators import observe

@observe()
def test():
    print("Hello, from the test function!")

test()

import ipdb
ipdb.set_trace()
```

Both `langfuse.auth_check()` and `test()` can trigger the error.
