### DISCUSSION TITLE
Deploy to heroku

### DISCUSSION THREAD

**Discussion by MarcoSteinke** [langfuse/langfuse#1814] [Support] [answered]
Hello, right now I am trying to deploy LangFuse to heroku. 

My heroku.yml : 

```yml
setup:
  addons:
    - plan: heroku-postgresql
      as: DATABASE
build:
  docker:
    web: Dockerfile
    worker: worker/Dockerfile
release:
  image: worker
run:
  web: node worker/dist/src/index.js
```

Project Structure of langfuse:

```
web/
..node_stuff/
..Dockerfile
..package.json

worker/
..stuff
..Dockerfile
..package.json

heroku.yml
package.json
```

When deploying to heroku I receive the following error:

```
remote: =!= There were problems parsing your heroku.yml. We've detected the following issues:
remote:
remote: build.docker.web references a Dockerfile that does not exist
```

My first thought was to set `build.docker.web`  in `heroku.yml` to `web/Dockerfile`. This resulted in the problem, that the workspace **worker** could no longer be found, because from what I understand the heroku deployment changes the directory to `web`.

```
WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available: could not resolve workspaces: io error: No such file or directory (os error 2)
remote:   x invalid scope: package worker not found
```

Does anybody have experience with deploying LangFuse to heroku?
