### DISCUSSION TITLE
Upcoming architecture changes for Langfuse 3.0 (self-hosted)

### DISCUSSION THREAD

**Discussion by maxdeichmann** [langfuse/langfuse#1902] [Announcements]
Hi all,

Langfuse is growing a lot, both in feature scope as well as in usage on single instances. Thus we plan for a couple of changes that will be released in Langfuse v3.

> [!IMPORTANT]
> **A Langfuse v3 is released**. Learn more [here](https://langfuse.com/changelog/2024-12-09-Langfuse-v3-stable-release).

We are currently required to mature our architecture as we are working on the following challenges:
✅ Building model-based evals, which requires us to run asynchronous tasks, rate limited, with failover capabilities.
🧑‍🍳 Improve performance as instances scale out.

I wanted to give you a heads up on upcoming changes which are required to make these features work. Currently, Langfuse contains a single Docker container, which takes care of everything we do. This was fast to set up Langfuse initially, but we need more technical capabilities now. In addition to the existing components (Docker container + Postgres database), we will add the following:

- Asynchronous processing in a [dedicated container](https://github.com/langfuse/langfuse/tree/main/worker)
- Redis container (for queues)
- OLAP storage (likely Clickhouse) to enable lower latencies on analytical queries and scale out storage for large and multi modal inputs outputs

If you self-host Langfuse, this means that we will likely advise to change to the following setup to be able to benefit from new infra changes easily. We are happy to hear your thoughts on this:

- Migrate from a container service (e.g. GCP Cloud Run) to a Virtual Machine to run docker-compose from there. Docker-compose helps to quickly bootstrap the new components.
- Either provide connection strings to the docker-compose for Redis, Postgres, and Clickhouse for managed databases or run all of them on the virtual machine as well.

Feel free to share your thoughts below on these topics:

- Tool choice: do you have experience with the tools mentioned above and have advise for us?
- Do you have ideas on how to make self-hosting easier in a multi-container, multi-database setup than docker compose?
- Do you have ideas on how a great migration path could look like?

Find more context in the last Langfuse [Townhall](https://youtu.be/WGERHcRnBYQ?feature=shared&t=1818) meeting. We will provide an easy to follow upgrade path for self-hosters once v3 is generally available. The infrastructure change does not affect public APIs, thus, users of Langfuse Cloud will not be affected by this change. Currently we pilot the async container & queue for the evals feature which is currently in public beta on Langfuse Cloud.

### _**UPDATE JULY 22nd**_

A more detailled overview of planned changes:

## **Architectures v2 vs. v3**
![CleanShot 2024-07-22 at 11 56 21](https://github.com/user-attachments/assets/d7966bc3-068a-461e-97db-427ae15d1e12)

- **Containers**
  - ```web``` container: hosts public api, and all resources for the user interface
  - ```worker``` container: asynchronous processes, no exposed ports
- **Databases**
  - ```Redis``` used as cache and queue
  - ```Postgres``` stores transactional data such as projects or API keys
  - ```Clickhouse``` stores tracing data generated by the SDKs. This database will do most of the processing as our server will insert all the SDK data and read it for tables and dashboards. 

Next to the core application, an **application load balancer** for TLS termination and routing of requests to the ```Web``` container is necessary. We use nginx but you can also use e.g. the fully managed AWS load balancer.

## **Upgrade path from v2 to v3**

Thousands of teams run on Langfuse (~400k docker pulls)
→ we aim to offer the easiest migration experience that is automated and documented

- Guidance on scalability of dockerized datastores, when are fully-managed datastores necessary, including at-rest encryption with custom keys
- Guidance of reliable auto-scaling configuration of the application and databases
- Migration script to move data from Postgres to Clickhouse, and/or to Clickhouse and a new Postgres instance

## **Application deployment**
![CleanShot 2024-07-22 at 11 51 15@2x](https://github.com/user-attachments/assets/ee5919cf-929b-41d7-b825-5634bdd158e7)

You will be able to deploy the containers kia Kubernetes or your own Container Deployment Service (such as Google Cloud Run) or via docker compose on a virtual machine. In either case, you will also be able to use dockerized databases or you can provide us with  connection strings for managed databases.

For low-volume/non-production deployments, dockerized DBs + docker compose is a sensible option to keep complexity low. We will publish guidance on when options 3 and 4 are necessary.

## **DB deployment**

Databases (see above): ```redis```, ```postgres```, ```clickhouse```

**Low-volume**

- All datastores are available as single docker containers
- Can be bundled in docker compose or EKS/ECS/K8S deployment

**High-volume / fully-managed → databases external of application cluster**

- **Redis**
  - No special requirements
  - AWS: we chose ElastiCache (Redis OSS) for a fully managed Redis instance
- **Postgres**
  - No special requirements compared to other applications.
  - AWS: we chose RDS for a fully-managed Postgres instance
- **Clickhouse**
  - Main data store, thus this database will scale the most.
  - AWS:
    - There is no RDS-equivalent for Clickhouse on AWS
    - We use [Clickhouse Cloud](https://clickhouse.com/cloud) which is the fully managed Clickhouse database managed by the Clickhouse team. This can be run on an AWS region of your choice with VPC peering for private access and data security.
    - There are potentially additional vendors for managed Clickhouse such as [DoubleCloud](https://double.cloud/services/managed-clickhouse/) or [Altinity](https://altinity.com/managed-clickhouse/).
    - Alternatively, you can run Clickhouse yourself in ECS, e.g. by using this [template](https://aws.amazon.com/solutions/implementations/clickhouse-cluster/).

We will provide guidance at which scale high-volume/fully-managed clickhouse is necessary. On hosted Langfuse, we are currently in the process of migrating to arrive at a scalable architecture. Once we are done with the migration, we will release 3.0. We will keep you posted here on updates regarding the migration.

## FAQ

- **Will v3 introduce any non-OSS components that require additional licensing?** No, all new infrastructure components (Clickhouse, Redis/Valkey, S3/minio) can be self-hosted without any non-FOSS dependency or licensing requirements. 
- **How long will there be security updates for v2?** We will support security updates for V2 until at least end of Q1 of 2025. If you require extended support, please reach out to us.

**Comment by MarkEdmondson1234** [comment]
As requested from Discord, my comment:

I really do not want to move off serverless infra to a dedicated VM, I'd say a major reason I chose Langfuse was its Cloud Run deployment I could couple with my existing AlloyDB. And perhaps AlloyDB is quick enough it doesn't need help with analytical queries. 

Cloud Run recently introduced side car containers so perhaps that is an option?
https://cloud.google.com/blog/products/serverless/cloud-run-now-supports-multi-container-deployments

There is a managed Redis option too but its a bit more pricy.

My serverless deployment at the moment I don't pay for Langfuse until I'm browsing the UI or its capturing traces, aside the already sunk cost of the database.

**Comment by noorvir** [comment]
The current docs advise not to use Docker Compose for production. I'm guessing that will change for v3? I would be great to have a ready to deploy docker compose that just needs an env file to get started. I'd use the cloud hosted service but have relatively strict data privacy requirements.

**Reply by clemra** [reply]
hi noorvir, clemens here, one of the founders. would love to understand your data privacy requirements better. we've just completed soc2 type 2 and iso 27001 + always willing to go further. A use case like yours is what we'd ideally want to support. feel free to send me an email: clemens@

**Reply by marcklingen** [reply]
If we switch to docker compose as the easiest self-hosted production deployment option, we'd include upgrade scripts to make it safe to upgrade versions and nudge to using dedicated databases instead of bundling them into the docker compose.

We are currently looking into solving similar to Airbyte: https://docs.airbyte.com/operator-guides/upgrading-airbyte#upgrading-on-docker

**Reply by verdverm** [reply]
FWIW, Deploying to k8s is relatively straight forward, docker compose/swarm should look similar. A Helm chart would likely be well received 

```yaml
apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: langfuse
      namespace: ts
      labels:
        app: langfuse
        tier: logmon
    spec:
      selector:
        matchLabels:
          app: langfuse
          tier: logmon
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      minReadySeconds: 5
      template:
        metadata:
          labels:
            app: langfuse
            tier: logmon
        spec:
          containers:
            - name: langfuse
              image: ghcr.io/langfuse/langfuse:2.11.3
              imagePullPolicy: Always
              env:
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: lf.psql.credentials.postgresql.acid.zalan.do
                      key: password
                - name: DATABASE_URL
                  value: postgres://lf:$(DATABASE_PASSWORD)@psql:5432/lf
                - name: HOSTNAME
                  value: 0.0.0.0
                - name: PORT
                  value: "3001"
                - name: NODE_ENV
                  value: production
                - name: NEXTAUTH_URL
                  value: http://localhost:3001
                - name: NEXTAUTH_SECRET
                  value: <redacted>
                - name: SALT
                  value: <redacted>
                - name: TELEMETRY_ENABLED
                  value: "true"
                - name: NEXT_PUBLIC_SIGN_UP_DISABLED
                  value: "false"
                - name: LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES
                  value: "false"
              resources:
                requests:
                  cpu: 200m
                  memory: 256Mi
              ports:
                - containerPort: 3001
                  protocol: TCP
          volumes: []
```
