### DISCUSSION TITLE
Enhance data in daily metrics api endpoint

### DISCUSSION THREAD

**Discussion by matthiaslau** [langfuse/langfuse#2209] [Ideas]
### Describe the feature or potential improvement

The daily metrics api endpoint is really helpful in our projects to integrate the usage summary for end users into the product interfaces. Besides the current data it would be really helpful to also add the costs per model to the data.usage and also the count of calls per model, to show the end users which models they are using the most.

**Comment by marcklingen** [comment]
great idea, added in #2219, will be released tomorrow

updated api response definition
```yaml
DailyMetrics:
    properties:
      data:
        type: list<DailyMetricsDetails>
        docs: A list of daily metrics, only days with ingested data are included.
      meta: pagination.MetaResponse
  DailyMetricsDetails:
    properties:
      date: date
      countTraces: integer
      countObservations: integer
      totalCost:
        type: double
        docs: Total model cost in USD
      usage: list<UsageByModel>
  UsageByModel:
    docs: Daily usage of a given model. Usage corresponds to the unit set for the specific model (e.g. tokens).
    properties:
      model: optional<string>
      inputUsage:
        type: integer
        docs: Total number of generation input units (e.g. tokens)
      outputUsage:
        type: integer
        docs: Total number of generation output units (e.g. tokens)
      totalUsage:
        type: integer
        docs: Total number of generation total units (e.g. tokens)
      countTraces: integer
      countObservations: integer
      totalCost:
        type: double
        docs: Total model cost in USD
```
