### DISCUSSION TITLE
Support for Custom Base URL Prefix in Langfuse (nextjs basepath)

### DISCUSSION THREAD

**Discussion by databill86** [langfuse/langfuse#2400] [Ideas]
### Describe the bug

I'm trying to run Langfuse on a custom path, for example: `http://mydomain:3000/langfuse`. Is there a way to use a base URL prefix?

### To reproduce

I am using Docker Compose to run Langfuse with the following environment variables:

```yaml
environment:
  - NODE_ENV=production
  - NEXTAUTH_URL=http://mydomain:3000/langfuse
  - LANGFUSE_BASEURL=http://mydomain:3000/langfuse
  ...
```

However, it seems that the custom base URL prefix is not taken into account, and langfuse always run at the root URL. Is there a configuration or workaround to achieve this?

Thank you!

### SDK and container versions

`image: ghcr.io/langfuse/langfuse:2.55.1`

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Moving to discussions as this is not a bug but rather a feature request. Open for contributions on this

**Comment by sbhadana** [comment]
I am having exactly the same requirement. As soon as the baseurl changes _next/static/css are not working and application just showing loading...

Its very important feature please help!

**Reply by marcklingen** [reply]
I am open for contributions on this. Is running langfuse on a subdomain an option for you?

**Reply by databill86** [reply]
I think most people hosting langfuse locally require this.

**Reply by marcklingen** [reply]
I often run langfuse locally and differentiate between services via port. Why do you think using a path is needed here?

**Reply by marcklingen** [reply]
Should be easy to add via basePath, see docs here: https://nextjs.org/docs/app/api-reference/next-config-js/basePath

If anyone is interested to add this, this for sure needs test coverage to make sure all features work end-to-end on a custom basePath

**Reply by sbhadana** [reply]
I am deploying on k8s where only sub domain path is an option to run it. 

Domain.com is fixed and used by my other project so subdomain could work.

**Reply by databill86** [reply]
Same for me. I will be running on k8s, and this is something I actually need.

**Reply by databill86** [reply]
FYI, as an example, litellm already support by adding a ENV variable: https://docs.litellm.ai/docs/proxy/deploy#1-customization-of-the-server-root-path-custom-proxy-base-url

**Reply by johngroves** [reply]
Plus one!

**Reply by ryokutech** [reply]
same for me

**Comment by ashutoshsaboo** [comment]
Ran into the same issue today :( , and was honestly amused to see that such a less mature project than langfuse - litellm support it, but not langfuse - given honestly langfuse is many many magnitudes more self-host friendly. I'd really appreciate if this can be added!

**Comment by jabbasj** [comment]
+1 would be nice to have this feature

**Comment by marioweid** [comment]
Same issue applies when  running langfuse in azure behind a Application Gateway with pathbased routing. This feature whould be so great.

Edit:
Did a little bit of reasearch and it seems like the basePath in Next.js needs to be present at build time (https://github.com/vercel/next.js/discussions/16059).
Which would mean if you want to run langfuse or any nextjs application behind a reverse proxy you need to compile the container yourself i guess.
Another approach would be to replace the webserver and move from node `server.js` to a nginx that serves the langfuse frontend.

**Comment by matined** [comment]
+1 it'd be helpful

**Comment by abdullah-retorio** [comment]
Any updates in this regard?

**Reply by marcklingen** [reply]
yes, coming today 🙌

https://github.com/langfuse/langfuse/issues/3342

**Comment by marcklingen** [comment]
We just released this in the [latest version](https://github.com/langfuse/langfuse/releases/tag/v2.79.0).

As @marioweid pointed out, this can only be set at build-time, thus you need to build the docker container from source. I included a snippet in the docs on how to do this: https://langfuse.com/docs/deployment/self-host#custom-base-path

As an alternative, I tested nginx rewrites which turned out to be inconsistent across the different client-side redirects within the application itself. Unfortunately, there is no simple solution that does not involve building from source.

cc @sbhadana as you mentioned yesterday that this is very relevant for you

**Reply by marioweid** [reply]
![image](https://github.com/user-attachments/assets/356bda9f-1858-4766-acfd-004e8254211e)
@marcklingen Should't the variables for a basepath of /langfuse be:

```
NEXT_PUBLIC_BASE_PATH="/langfuse"
NEXTAUTH_URL="https://yourdomain.com/langfuse/api/auth"
```

**Reply by marcklingen** [reply]
Oh thanks for the heads up, the docs are inconsistent here, fixed it: https://github.com/langfuse/langfuse-docs/commit/0144c8a5189e5a4e48c6a5251f3796c3303526bc

**Reply by aaktaev** [reply]
Hi, @marcklingen ,

Thank you for this fix.

I was able successfully deploy langfuse with custom BASE PATH.
Only thing - after clicking to "Sign UP" button with filled fields it redirects to "/" instead of domain with custom base path.

Expected:

```
POST https://domain.com/custom_base_path/api/auth/callback/credentials -> https://domain.com/custom_base_path
```
But now it works this way:
```
POST https://domain.com/custom_base_path/api/auth/callback/credentials -> https://domain.com/
```

**Comment by abdullah-retorio** [comment]
Hello, I want to share my self-hosting experience with you. I hope this guide helps you!

**You can self-host Langfuse with Envoy as an SSL gateway using docker-compose.**

Here you can find an example `envoy.yaml`, `docker-compose.yaml` and `.env` files. You can save these files in the same folder for easier use.

- If you are running on a VM
  - Be sure that your VM's `80, 443, 15432, and 9901` ports are open for inbound request traffic.
  - Be sure that you are using a persistent disk to have `<your_postgres_db_data_folder>`
  - `<your_nextauth_url>` should be the same URL that you connect to Langfuse UI. For example, `https://langfuse.X.Y`

- These configurations let you connect your PostgresDB data via TLS-secured `port 15432` with username/password on tools like pgAdmin.
- Please change variables written in the format of `<a_b_c>` with your values.
- Langfuse will be served in base path(/). You can reach it via `https://langfuse.X.Y`

**.env**

```.env
ENVOY_YAML_PATH=<your_envoy_yaml_path>
ENVOY_SSL_DATA_PATH=<your_ssl_data_folder>

POSTGRES_DATA_PATH=<your_postgres_db_data_folder>
POSTGRES_USER=<your_postgres_user>
POSTGRES_PASSWORD=<your_postgres_password>

LANGFUSE_DB=<your_langfuse_db>
LANGFUSE_NEXTAUTH_SECRET=<your_nextauth_secret>
LANGFUSE_NEXTAUTH_URL=<your_nextauth_url>
LANGFUSE_SALT=<your_langfuse_salt>
````

**envoy.yaml**

```yaml
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901

static_resources:
  listeners:
  - name: listener_http
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                redirect:
                  path_redirect: "/"
                  https_redirect: true
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  - name: listener_https
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 443
    filter_chains:
    - filters:
      - name: envoy.filters.network.http_connection_manager
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          stat_prefix: ingress_https
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: langfuse_cluster
          http_filters:
          - name: envoy.filters.http.router
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      transport_socket:
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
          common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename:  "/etc/envoy/ssl/<your_cert_file>"
                private_key:
                  filename: "/etc/envoy/ssl/<your_private_key>"
              validation_context:
                trusted_ca:
                  filename: "/etc/envoy/ssl/<your_ca_bundle>"

  - name: listener_postgres
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 15432
    filter_chains:
    - filters:
      - name: envoy.filters.network.tcp_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
          stat_prefix: postgres_tcp
          cluster: postgres_cluster
      transport_socket:
        name: "starttls"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.starttls.v3.StartTlsConfig
          tls_socket_config:
            common_tls_context:
              tls_certificates:
              - certificate_chain:
                  filename: "/etc/envoy/ssl/<your_cert_file>"
                private_key:
                  filename: "/etc/envoy/ssl/<your_private_key>"
              validation_context:
                trusted_ca:
                  filename: "/etc/envoy/ssl/<your_ca_bundle>"

  clusters:
  - name: langfuse_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: langfuse_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: langfuse
                port_value: 3000

  - name: postgres_cluster
    connect_timeout: 0.25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    load_assignment:
      cluster_name: postgres_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: postgres
                port_value: 5432
```

**docker-compose.yaml**

```yaml

services:
  postgres:
    image: postgres:16-bookworm
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 5432:5432
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${LANGFUSE_DB}
    networks:
      - docker_network

  langfuse:
    image: langfuse/langfuse:2
    restart: always
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${LANGFUSE_DB}
      NEXTAUTH_SECRET: ${LANGFUSE_NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${LANGFUSE_NEXTAUTH_URL}
      SALT: ${LANGFUSE_SALT}
      TELEMETRY_ENABLED: ${TELEMETRY_ENABLED:-true}
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: ${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
    depends_on:
      - postgres
    networks:
      - docker_network
   
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    restart: always
    depends_on:
      - langfuse
      
    ports:
      - 80:80
      - 443:443
      - 15432:15432
      - 9901:9901
    networks:
      - docker_network
    volumes:
      - ${ENVOY_YAML_PATH}:/etc/envoy/envoy.yaml
      - ${ENVOY_SSL_DATA_PATH}/<your_cert_file>:/etc/envoy/ssl/<your_cert_file>
      - ${ENVOY_SSL_DATA_PATH}/<your_private_key>:/etc/envoy/ssl/<your_private_key>
      - ${ENVOY_SSL_DATA_PATH}/<your_ca_bundle>:/etc/envoy/ssl/<your_ca_bundle>

networks:
  docker_network:
    driver: bridge
```

**One extra helper:** If you want to upgrade your Langfuse version(for v2) without stopping and restarting your docker-compose, you can use this approach:

- Change docker-compose.yaml image names with
  - langfuse/langfuse:2 -> langfuse:latest
  - postgres:16-bookworm -> postgres:latest
  - envoyproxy/envoy:v1.31-latest -> envoy:latest
  
- Save this bash script into the same folder with the other files above.

- Run command `./upgrade-container.sh <langfuse | postgres | envoy | all>`
  - In the first run, you must run `./upgrade-container.sh all` to pull and tag them the first time.
  - When you run `docker compose up`, it checks your locally pulled images first. So we can pull an image, retag it, and restart with the latest.
  
- You can add some aliases in `.bashrc` file for Linux and `.zshrc` file for MacOS. For instance,
  - `alias wakeup_docker_compose="<folder_absolute_path_contains_your_upgrade-container>/upgrade-container.sh all"`
  - `alias upgrade_langfuse="<folder_absolute_path_contains_your_upgrade-container>/upgrade-container.sh langfuse"`
  - `alias upgrade_envoy="<folder_absolute_path_contains_your_upgrade-container>/upgrade-container.sh envoy"`
  - `alias upgrade_postgres="<folder_absolute_path_contains_your_upgrade-container>/upgrade-container.sh postgres"`

**upgrade-container.sh**

```bash
#!/bin/sh

SERVICE=$1

pull_langfuse() {
  # Removes old tagged langfuse:latest if exists
  docker rmi langfuse:latest || true
  
  # Pulls the latest langfuse:2
  docker pull langfuse/langfuse:2
  
  # Retags the latest langfuse
  docker tag langfuse/langfuse:2 langfuse:latest
}

pull_postgres() {
  # Removes old tagged postgres:latest if exists
  docker rmi postgres:latest || true
  
  # Pulls the latest posgtres:16-bookworm
  docker pull posgtres:16-bookworm
  
  # Retags the latest postgres
  docker tag posgtres:16-bookworm postgres:latest
}

pull_envoy() {
  # Removes old tagged envoy:latest if exists
  docker rmi envoy:latest || true
  
  # Pulls the latest envoyproxy/envoy:v1.31-latest
  docker pull envoyproxy/envoy:v1.31-latest
  
  # Retags the latest envoy
  docker tag envoyproxy/envoy:v1.31-latest envoy:latest
}

# Check if the service is langfuse
if [ "$SERVICE" = "langfuse" ]; then
    pull_langfuse
    docker compose -f <folder_absolute_path_contains_your_docker_compose>/docker-compose.yaml up -d langfuse 
fi

# Check if the service is postgres
if [ "$SERVICE" = "postgres" ]; then
    pull_postgres
    docker compose -f <folder_absolute_path_contains_your_docker_compose>/docker-compose.yaml up -d postgres
fi

# Check if the service is envoy
if [ "$SERVICE" = "envoy" ]; then
    pull_envoy
    docker compose -f <folder_absolute_path_contains_your_docker_compose>/docker-compose.yaml up -d envoy 
fi

# Check if the service is all
if [ "$SERVICE" = "all" ]; then
    pull_postgres
    pull_langfuse
    pull_envoy

    docker compose -f <folder_absolute_path_contains_your_docker_compose>/docker-compose.yaml up -d 
fi
```
