### DISCUSSION TITLE
Deployment on K8s

### DISCUSSION THREAD

**Discussion by nithin1995** [langfuse/langfuse#2735] [Support] [answered]
Hi Team, 

When I try to deploy langfuse on a K8 cluster, I get the following error logs on my webserver pod
```
Script executed successfully.
Prisma schema loaded from packages/shared/prisma/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "rahul-postgres-postgresql:5432"

225 migrations found in prisma/migrations

Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The 20240528214728_add_cursor_index_07 migration started at 2024-07-24 09:08:03.995844 UTC failed


Applying database migrations failed. This is mostly caused by the database being unavailable.
Exiting...
```
On the db pod, I get the following log message
```
2024-07-25 04:28:09.400 GMT [213262] LOG:  could not receive data from client: Connection reset by peer
2024-07-25 04:28:52.364 GMT [213321] LOG:  could not receive data from client: Connection reset by peer
2024-07-25 04:30:39.517 GMT [213479] LOG:  could not receive data from client: Connection reset by peer
```

I created my own postgres db using bitnami and am trying to deploy langfuse webserver without deploying db. My db pod is running.
My langfuse yaml file

```
langfuse:
  nextauth:
    url: localhost:3000
    secret: changeme
  salt: changeme
  telemetryEnabled: true
service:
  type: ClusterIP
  additionalLabels: []
ingress:
  enabled: false
  annotations: []
postgresql:
  deploy: false
  auth:
    username: postgres
    password: <password>
    database: postgres
  host: rahul-postgres-postgresql
  directUrl: postgresql://postgres:<password>@<db pod_name>:5432/postgres
  shadowDatabaseUrl: postgresql://postgres:<password>@<db pod_name>:5432/postgres
```

Both the pods are running on the same cluster. I couldn't figure out the reason for this error, can anyone help me?

**Comment by dosubot** [comment]
Hey @nithin1995! I'm here to help you with the langfuse deployment issue. I'm a bot that can assist with bug fixes, answering questions, and guiding you to become a contributor. Let's figure this out together!


To resolve the database migration issues you're encountering when deploying Langfuse on your Kubernetes cluster, you can follow these steps:

1. **Check and Resolve Failed Migrations:**
   You need to manually resolve the failed migrations in your PostgreSQL database. Connect to your PostgreSQL database and execute the following SQL script to delete the specific failed migrations from the `_prisma_migrations` table:

   ```sql
   DO $$
   BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = '_prisma_migrations') THEN
     DELETE FROM _prisma_migrations
     WHERE migration_name IN ('20240528214728_add_cursor_index_07');
    END IF;
   END $$;
   ```

2. **Configure Environment Variables:**
   Ensure that you have configured the `DIRECT_URL` and `SHADOW_DATABASE_URL` environment variables correctly in your Kubernetes deployment configuration. This allows you to use a different user for migrations or use connection pooling on `DATABASE_URL`.

   Here is an example of how to set these environment variables in your Kubernetes deployment configuration:

   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: langfuse
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: langfuse
     template:
       metadata:
         labels:
           app: langfuse
       spec:
         containers:
         - name: langfuse
           image: langfuse/langfuse:latest
           env:
           - name: DATABASE_URL
             value: "postgresql://postgres:<password>@rahul-postgres-postgresql:5432/postgres"
           - name: DIRECT_URL
             value: "postgresql://postgres:<password>@rahul-postgres-postgresql:5432/postgres"
           - name: NEXTAUTH_URL
             value: "http://localhost:3000"
           - name: NEXTAUTH_SECRET
             value: "changeme"
           - name: SALT
             value: "changeme"
           - name: SHADOW_DATABASE_URL
             value: "postgresql://postgres:<password>@rahul-postgres-postgresql:5432/postgres"
           ports:
           - containerPort: 3000
   ```

3. **Verify Connectivity and Network Policies:**
   Ensure that the Langfuse webserver pod can connect to the PostgreSQL database pod. You can use a simple connectivity test from the Langfuse webserver pod to the PostgreSQL database pod:

   ```sh
   kubectl exec -it <langfuse-webserver-pod> -- curl -s -o /dev/null -w "%{http_code}" postgresql://rahul-postgres-postgresql:5432
   ```

   Additionally, verify that the network policies allow traffic between the Langfuse webserver pod and the PostgreSQL database pod. Here is an example of a network policy:

   ```yaml
   apiVersion: networking.k8s.io/v1
   kind: NetworkPolicy
   metadata:
     name: allow-langfuse-to-postgres
     namespace: <your-namespace>
   spec:
     podSelector:
       matchLabels:
         app: postgresql
     ingress:
     - from:
       - podSelector:
           matchLabels:
             app: langfuse-webserver
       ports:
       - protocol: TCP
         port: 5432
   ```

By following these steps, you should be able to resolve the database migration issues and ensure proper connectivity between the Langfuse webserver pod and the PostgreSQL database pod <sup>[[1]](https://github.com/langfuse/langfuse/blob/main/packages/shared/scripts/cleanup.sql)</sup><sup>[[2]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/deployment/self-host.mdx)</sup><sup>[[3]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/integrations/langflow.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by nithin1995** [reply]
@dosu where should this configuration be applied?
```
Additionally, verify that the network policies allow traffic between the Langfuse webserver pod and the PostgreSQL database pod. Here is an example of a network policy:

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-langfuse-to-postgres
  namespace: <your-namespace>
spec:
  podSelector:
    matchLabels:
      app: postgresql
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: langfuse-webserver
    ports:
    - protocol: TCP
      port: 5432
```
Is it on the webserver pod or db pod?

**Reply by dosubot** [reply]
The network policy configuration should be applied to the PostgreSQL database pod. This policy allows ingress traffic from the Langfuse webserver pod to the PostgreSQL database pod on port 5432.

Here is the configuration again for clarity:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-langfuse-to-postgres
  namespace: <your-namespace>
spec:
  podSelector:
    matchLabels:
      app: postgresql
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: langfuse-webserver
    ports:
    - protocol: TCP
      port: 5432
```

Apply this configuration to ensure that the PostgreSQL database pod allows traffic from the Langfuse webserver pod.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by nithin1995** [reply]
It specifically failing in the migrations, I think its not a database connection issue. I can see some migrations happenning and then this one failed. I also tried spinning up a fresh postgres instance with no data in it. still facing the same issue, can anyone help?

**Reply by dosubot** [reply]
To resolve the migration issue with Langfuse on your Kubernetes cluster, specifically the failure of the `20240528214728_add_cursor_index_07` migration, you can follow these steps:

1. **Check Database Connection and Permissions:**
   Ensure that the database user has the necessary permissions to perform migrations. You might need to use a different user for migrations or configure connection pooling.

2. **Use `DIRECT_URL` for Migrations:**
   Set the `DIRECT_URL` environment variable to use a different user for migrations if needed. This user should have the necessary permissions and long timeouts for large deployments.

   ```yaml
   env:
     - name: DIRECT_URL
       value: "your_migration_user_connection_string"
   ```

3. **Disable Automatic Migrations Temporarily:**
   If the migration is failing repeatedly, you can disable automatic migrations temporarily by setting the `LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED` environment variable to `true`.

   ```yaml
   env:
     - name: LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED
       value: "true"
   ```

4. **Manually Apply the Migration:**
   Manually apply the migration using the steps provided in the documentation. This involves cloning the repository, setting up the environment, and running the migration script.

   ```bash
   # Clone the Langfuse repository
   git clone https://github.com/langfuse/langfuse.git

   # Navigate to the Langfuse directory
   cd langfuse

   # Install all dependencies
   pnpm i

   # Create an .env file
   cp .env.dev.example .env

   # Edit the .env to connect to your database from your machine
   # Replace with your database connection string
   DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres

   # Execute the migration
   pnpm run models:migrate
   ```

5. **Re-enable Automatic Migrations:**
   Once the migration is successfully applied, re-enable automatic migrations by setting `LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED` back to `false`.

   ```yaml
   env:
     - name: LANGFUSE_AUTO_POSTGRES_MIGRATION_DISABLED
       value: "false"
   ```

By following these steps, you should be able to resolve the migration issue with Langfuse on your Kubernetes cluster <sup>[[1]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/deployment/self-host.mdx)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
