### DISCUSSION TITLE
Change port database in file docker-compose.yml

### DISCUSSION THREAD

**Discussion by hungvipqt15** [langfuse/langfuse#2909] [Support] [answered]
The port 5432 for database postgres in my server is busy and I do not want to stop this port. Help me change the port database in file docker-compose.yml so that it can run smoothly:

services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:4000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local

**Comment by dosubot** [comment]
To change the PostgreSQL port in your `docker-compose.yml` file to avoid conflicts with port 5432, you need to update the port mapping for the `db` service and the `DATABASE_URL` environment variable for the `langfuse-server` service. Here is how you can modify your file to use port 5433 instead:

```yml
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:4000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

In this example, the `db` service is now mapped to port 5433 on the host, and the `DATABASE_URL` environment variable for the `langfuse-server` service has been updated to use port 5433 <sup>[[1]](https://github.com/langfuse/langfuse/blob/main/docker-compose.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
