### DISCUSSION TITLE
Langfuse 2.74.0 integration with Flowise 2.0.5

### DISCUSSION THREAD

**Discussion by harshad-c1** [langfuse/langfuse#3120] [Support]
Hi,

I am a starter - evaluating options. 
Have langfuse and flowise locally hosted on my computer using docker. No changes to any one of them. 
Trying to integrate langfuse with flowise in order to get some performance data + traces.
For integration - I followed steps in https://langfuse.com/docs/integrations/flowise and did some test chats in flowise chat flow but am not getting any activity in langfuse. No logs regarding sending data to langfuse is seen in flowise docker logs. No logs in langfuse after startup.

Feel like I am missing something in the setup. But cannot put my finger on it. Any guidance to solve this would help

Thanks

**Comment by dosubot** [comment]
Hey @harshad-c1,

I'm here to help you with any bugs, questions, or becoming a contributor. Let's work together to solve this!

[Dosu](https://dosu.dev)


I found a similar unsolved discussion that might be relevant to your issue: [Can't see any traces or logs when running Langfuse locally](https://github.com/orgs/langfuse/discussions/2377) <sup>[[1]](https://github.com/orgs/langfuse/discussions/2377)</sup>.

To successfully integrate Langfuse 2.74.0 with Flowise 2.0.5 using Docker and obtain performance data and traces, follow these steps:

1. **Verify Integration**: Ensure that your application is correctly integrated with Langfuse. Follow the [quickstart guide](https://langfuse.com/docs/get-started) to verify your setup.

2. **Check API Credentials**: Make sure that the API credentials used in your application match those created in your Langfuse project settings.

3. **Inspect Tracing Configuration**: Ensure that your tracing configuration is correctly set up. For example, verify that the `LANGFUSE_HOST` (Python) or `LANGFUSE_BASEURL` (JS/TS) is set to the correct endpoint.

4. **Review Logs**: Check the logs of your application to see if there are any errors related to Langfuse. This can help identify issues with the integration or network connectivity. Optionally, you can enable debug logging to get more detailed information.

5. **Manual Flushing**: If you are using short-lived applications like serverless functions, local batch scripts, or Jupyter Notebooks, ensure that you are manually flushing the events before the application exits. This is important to avoid losing events. Read more on this [here](https://langfuse.com/docs/tracing).

6. **Network Issues**: Check for any network issues that might be preventing your application from sending data to Langfuse. Ensure that your firewall or network settings allow outbound connections to Langfuse endpoints.

7. **Batching Configuration**: In high throughput applications, verify the batching configuration to ensure that events are being sent in a timely manner. You can adjust the `flushAt` and `flushInterval` settings to suit your needs.

8. **Docker Compose Setup**: If you prefer to self-host Langfuse, you can run both Langfuse and Flowise using Docker Compose. By combining the two docker-compose files, you can streamline the networking between them. Here is an example configuration:

```yaml
version: "3.5"

services:
  flowise:
    image: flowise/flowise:2.0.5
    ports:
      - "3001:3001"
    environment:
      - LANGFUSE_SECRET_KEY=your_secret_key
      - LANGFUSE_PUBLIC_KEY=your_public_key
      - LANGFUSE_HOST=http://langfuse-server:3000
    command: flowise start

  langfuse-server:
    image: ghcr.io/langfuse/langfuse:2.74.0
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

To test the connectivity between Flowise and Langfuse, run the following command:

```sh
docker compose exec flowise python -c "import requests, os; addr = os.environ.get('LANGFUSE_HOST'); print(addr); res = requests.get(addr, timeout=5); print(res.status_code)"

# which should output the following:
# http://langfuse-server:3000
# 200
```

9. **Mapping of Flowise to Langfuse**: The integration automatically maps the following fields from Flowise to Langfuse:
   - `chatId` from Flowise maps to `sessionId` in Langfuse.

10. **Override Config**: You can pass additional parameters as `overrideConfig` to the Langfuse API. This can be used to pass additional information to Langfuse, such as `userId` for user-level tracking. Example:

```json
{
  "question": "hi there",
  "overrideConfig": {
    "analytics": {
      "langFuse": {
        "userId": "user1"
      }
    }
  }
}
```

By following these steps, you should be able to identify and resolve the issue preventing traces from appearing in the Langfuse dashboard. For more detailed information, you can refer to the [Langfuse documentation](https://langfuse.com/docs) <sup>[[2]](https://github.com/langfuse/langfuse-docs/blob/main/pages/faq/all/missing-traces.mdx)</sup><sup>[[3]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/integrations/langflow.mdx)</sup><sup>[[4]](https://github.com/langfuse/langfuse-docs/blob/main/pages/docs/integrations/flowise.mdx)</sup><sup>[[5]](https://github.com/langfuse/langfuse/blob/main/README.md)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
