### DISCUSSION TITLE
How to run langfuse locally while using a hosted database

### DISCUSSION THREAD

**Discussion by wil0u** [langfuse/langfuse#3465] [Support] [answered]
Is it possible to use langfuse such that users access the langfuse dashboard from their local machine and only the database is hosted and persisted online (maybe that is the default use case idk) ? 
For instance, I have a gen AI app somewhere that I want to monitor, I plugged langfuse on this app. Then I have a team of Data scientists that want to access the traces generated by this app from their machine and take some actions or just analyse the data.
My idea would be to self host a postgres database somewhere within a cloud plateform, for instance railway. Then clone the langfuse project on the PCs of my team and configure langfuse interface so that it fetches data from this postgres database on railway. Would it work ?

**Comment by dosubot** [comment, marked as answer]
Bonjour @wil0u! I'm here to help you with any questions or issues you have. Let's tackle this together!


Yes, it is possible to use Langfuse such that users access the Langfuse dashboard from their local machine while the database is hosted and persisted online. You can self-host a PostgreSQL database on a cloud platform like Railway and configure Langfuse to fetch data from this database.

From the provided document:

> Langfuse requires a persistent Postgres database to store its state. You can use a managed service on AWS, Azure, or GCP, or host it yourself. Once the database is ready, keep the connection string handy. At least version 12 is required.

You can follow the self-hosting instructions to set up Langfuse with a cloud-hosted PostgreSQL database. Here is a brief overview of the steps:

1. **Prepare the PostgreSQL Database**: Ensure you have a PostgreSQL database ready on a cloud platform like Railway, AWS, Azure, or GCP.
2. **Deploy the Langfuse Docker Container**: Use Docker to deploy the Langfuse server on your local machine or any other infrastructure.
3. **Configure Environment Variables**: Set the necessary environment variables, including `DATABASE_URL`, to connect Langfuse to your cloud-hosted PostgreSQL database.

For detailed instructions, refer to the [Self-Hosting Langfuse documentation](https://langfuse.com/docs/self-host) <sup>[[1]](https://github.com/langfuse/langfuse/blob/main/README.md)</sup><sup>[[2]](https://langfuse.com/docs/self-host)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

**Reply by marcklingen** [reply]
The ai answer here is perfect. If you want to use Langfuse locally, I'd recommend to use [docker compose](https://langfuse.com/docs/deployment/local) and edit the compose config to use your cloud-hosted database:

1. You need to have docker desktop installed
2. Save the following as docker-compose.yml in a folder, you need to update DATABASE_URL to point to your hosted database
      ```yml
      services:
        langfuse-server:
          image: langfuse/langfuse:2
          depends_on:
            db:
              condition: service_healthy
          ports:
            - "3000:3000"
          environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres # update connection string here
            - NEXTAUTH_SECRET=mysecret
            - SALT=mysalt
            - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
            - NEXTAUTH_URL=http://localhost:3000
      ```
3. Run locally via `docker compose up`

Please note:
- This might be slow at scale as Langfuse is built assuming that the interface/api runs in the same data center as the database.
- I'd generally recommend to deploy the langfuse application alongside the database. Also, you will need to make sure that all users are on the same version.
