### DISCUSSION TITLE
Help needed with CustomSSOProvider Configuration for GitHub Enterprise

### DISCUSSION THREAD

**Discussion by jay0129** [langfuse/langfuse#4413] [Support]
**Description:**

I am seeking help with configuring the `CustomSSOProvider` for our GitHub Enterprise (GHE) environment. Here are the details of what I have attempted and encountered.

**Current Setup:**

- We are using GitHub Enterprise instead of gitHub.com. Here is the relevant documentation: [GitHub Enterprise Server 3.12](https://docs.github.com/enterprise-server@3.12).

**Initial Implementation Approach:**

- As `GitHubProvider` with endpoint overriding is not supported, I decided to try the `CustomSSOProvider`.  However, this approach doesn't seem to be working as expected.

**Environment Variables for Langfuse Web Server:**

```yaml
- name: AUTH_CUSTOM_CLIENT_ID
  value: "xxx"
- name: AUTH_CUSTOM_CLIENT_SECRET
  value: "yyy"
- name: AUTH_CUSTOM_ALLOW_ACCOUNT_LINKING
  value: "true"
- name: AUTH_CUSTOM_CLIENT_ISSUER
  value: "https://git.mycom.com"
- name: AUTH_CUSTOM_NAME
  value: "GHE"
- name: AUTH_CUSTOM_SCOPE
  value: "read:user user:email"
```

**Previous Attempts:**
- I have attempted both the GitHub App (with email read permission enabled) and GitHub OAuth configurations.

**Additional Information:**
- I've included a screenshot for reference. The button seems to be missing:
<img width="598" alt="image" src="https://github.com/user-attachments/assets/81914a49-1003-4a13-9bd5-944f733784d0">

---

If further information is needed, or there are specific questions you'd like to ask, feel free to let me know!
