### DISCUSSION TITLE
Running Langfuse behind Nginx with custom base path

### DISCUSSION THREAD

**Discussion by hookenful** [langfuse/langfuse#4444] [Support] [answered]
Hi, I am proxying langfuse through nginx. Having this when navigate path. Getting 404 on that path. What did I miss? 

```
location /langfuse
        {
            proxy_pass http://langfuse:3000;
        }
 ```

`NEXT_PUBLIC_BASE_PATH=/langfuse`

Maybe I should do some rewrite on nginx? Something like that 
```
			rewrite ^/langfuse/(.*)$ /$1 break;
```

**Comment by dosubot** [comment]
Hey there, @hookenful! I'm here to help you with any bugs, questions, or contributions you might have. Let's get to the bottom of this together.


I found a similar discussion that might be helpful: [Running Langfuse in Kubernetes](https://github.com/langfuse/langfuse/discussions/1417#discussioncomment-8792247). In that thread, deploying Langfuse with a root path in the nginx ingress was suggested as a solution. Here's an example configuration that might help you:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: class2
  tls:
  - hosts:
    - <url>
    secretName: <secret name>    
  rules:
  - host: <url>
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: langfuse
            port:
              number: 3000
```

For your Nginx configuration, you should indeed use a rewrite rule to handle the base path. Here's how you can modify your Nginx configuration:

```nginx
location /langfuse {
    rewrite ^/langfuse/(.*)$ /$1 break;
    proxy_pass http://langfuse:3000;
}
```

Make sure that your `NEXT_PUBLIC_BASE_PATH` is set correctly to `/langfuse`, as you have done. This setup should help in correctly routing the requests through Nginx.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*
