### DISCUSSION TITLE
Self-hosting in VM does not work

### DISCUSSION THREAD

**Discussion by kidaufo** [langfuse/langfuse#4833] [Support]
I'm trying to self-host langfuse v3 in a VM (EC2 instance) using docker-compose, but I can't connect to http://<instance-ip>:3000 from local browser. I could connect to http://localhost:3000 (which is a bit weird) but I can't log anything. 

I found the document here, but I doesn't mention which file should be modified.
https://langfuse.com/faq/all/debug-docker-deployment

Could you please provide guidance on how to properly configure it?

**Comment by dosubot** [comment]
Hey @kidaufo! I'm here to help you with any bugs or questions you have about Langfuse. Let's work together to resolve your self-hosting issue.


To resolve the issue with self-hosting Langfuse on your EC2 instance, follow these steps to configure your Docker Compose file:

1. **Set `HOSTNAME`**: Modify your Docker Compose file to include `HOSTNAME=0.0.0.0` in the environment variables. This allows Langfuse to accept connections from any IP address. Here's an example:

    ```yaml
    services:
      langfuse:
        environment:
          - HOSTNAME=0.0.0.0
    ```

2. **Check `NEXTAUTH_URL`**: Ensure the `NEXTAUTH_URL` environment variable is set to the URL you are using to access Langfuse, such as `http://<instance-ip>:3000`. Update your Docker Compose file accordingly:

    ```yaml
    services:
      langfuse:
        environment:
          - NEXTAUTH_URL=http://<instance-ip>:3000
    ```

3. **Port Exposure**: Make sure port 3000 is correctly exposed in your Docker Compose file:

    ```yaml
    services:
      langfuse:
        ports:
          - "3000:3000"
    ```

4. **Security Group Settings**: Ensure your EC2 instance's security group allows inbound traffic on port 3000. You need to add a rule to the security group to permit traffic on this port.

By making these adjustments, you should be able to access Langfuse at `http://<instance-ip>:3000` from your local browser <sup>[[1]](https://langfuse.com/self-hosting/v2/deployment-guide)</sup><sup>[[2]](https://langfuse.com/docs/deployment/v3/guides/docker-compose)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/d70385ea-9b71-433b-92d3-bb8d0f7f22ba?feedback_type=other)</sup>
