### DISCUSSION TITLE
Setup for scale with docker compose

### DISCUSSION THREAD

**Discussion by takefy-dev** [langfuse/langfuse#4885] [Support]
I have setup langfuse v3 but with medium scale it always crash like always crash even tho i have really good machine with over 30 core and 64 gb ram + 500 gb storage.

I use this docker compose 
```
services:
  langfuse-worker:
    image: 'langfuse/langfuse-worker:3'
    restart: always
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    ports:
      - '3030:3030'
    environment:
      DATABASE_URL: 'URL'
      SALT: salt
      ENCRYPTION_KEY: key
      TELEMETRY_ENABLED: '${TELEMETRY_ENABLED:-true}'
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: '${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-true}'
      CLICKHOUSE_MIGRATION_URL: '${CLICKHOUSE_MIGRATION_URL:-clickhouse://clickhouse:9000}'
      CLICKHOUSE_URL: '${CLICKHOUSE_URL:-http://clickhouse:8123}'
      CLICKHOUSE_USER: '${CLICKHOUSE_USER:-clickhouse}'
      CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD:-clickhouse}'
      CLICKHOUSE_CLUSTER_ENABLED: '${CLICKHOUSE_CLUSTER_ENABLED:-false}'
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: '${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}'
      LANGFUSE_S3_EVENT_UPLOAD_REGION: '${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}'
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID:-minio}'
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}'
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: '${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9000}'
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: '${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}'
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: '${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}'
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: '${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}'
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: '${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}'
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID:-minio}'
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}'
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: '${LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT:-http://minio:9000}'
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: '${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}'
      LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: '${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
      REDIS_AUTH: '${REDIS_AUTH:-myredissecret}'
  langfuse-web:
    image: 'langfuse/langfuse:3'
    restart: always
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'URL'
      SALT: ac81719f08131a7c9ae74ff98a9bf2621e76100199ac7663fe613255909f9198
      ENCRYPTION_KEY: 2cd0014856ef5a28693c3ef7817db814c6cac6149fc5768a0db09a9cfd3236b0
      TELEMETRY_ENABLED: '${TELEMETRY_ENABLED:-true}'
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: '${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-true}'
      CLICKHOUSE_MIGRATION_URL: '${CLICKHOUSE_MIGRATION_URL:-clickhouse://clickhouse:9000}'
      CLICKHOUSE_URL: '${CLICKHOUSE_URL:-http://clickhouse:8123}'
      CLICKHOUSE_USER: '${CLICKHOUSE_USER:-clickhouse}'
      CLICKHOUSE_PASSWORD: '${CLICKHOUSE_PASSWORD:-clickhouse}'
      CLICKHOUSE_CLUSTER_ENABLED: '${CLICKHOUSE_CLUSTER_ENABLED:-false}'
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: '${LANGFUSE_S3_EVENT_UPLOAD_BUCKET:-langfuse}'
      LANGFUSE_S3_EVENT_UPLOAD_REGION: '${LANGFUSE_S3_EVENT_UPLOAD_REGION:-auto}'
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID:-minio}'
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}'
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: '${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9000}'
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: '${LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE:-true}'
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: '${LANGFUSE_S3_EVENT_UPLOAD_PREFIX:-events/}'
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: '${LANGFUSE_S3_MEDIA_UPLOAD_BUCKET:-langfuse}'
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: '${LANGFUSE_S3_MEDIA_UPLOAD_REGION:-auto}'
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: '${LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID:-minio}'
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: '${LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY:-miniosecret}'
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: '${LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT:-http://minio:9000}'
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: '${LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE:-true}'
      LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: '${LANGFUSE_S3_MEDIA_UPLOAD_PREFIX:-media/}'
      REDIS_HOST: '${REDIS_HOST:-redis}'
      REDIS_PORT: '${REDIS_PORT:-6379}'
      REDIS_AUTH: '${REDIS_AUTH:-myredissecret}'
      NEXTAUTH_URL: 'http://localhost:3000'
      NEXTAUTH_SECRET: mysecret
      LANGFUSE_INIT_ORG_ID: '${LANGFUSE_INIT_ORG_ID:-}'
      LANGFUSE_INIT_ORG_NAME: '${LANGFUSE_INIT_ORG_NAME:-}'
      LANGFUSE_INIT_PROJECT_ID: '${LANGFUSE_INIT_PROJECT_ID:-}'
      LANGFUSE_INIT_PROJECT_NAME: '${LANGFUSE_INIT_PROJECT_NAME:-}'
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: '${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}'
      LANGFUSE_INIT_PROJECT_SECRET_KEY: '${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}'
      LANGFUSE_INIT_USER_EMAIL: '${LANGFUSE_INIT_USER_EMAIL:-}'
      LANGFUSE_INIT_USER_NAME: '${LANGFUSE_INIT_USER_NAME:-}'
      LANGFUSE_INIT_USER_PASSWORD: '${LANGFUSE_INIT_USER_PASSWORD:-}'
      LANGFUSE_SDK_CI_SYNC_PROCESSING_ENABLED: '${LANGFUSE_SDK_CI_SYNC_PROCESSING_ENABLED:-false}'
      LANGFUSE_READ_FROM_POSTGRES_ONLY: '${LANGFUSE_READ_FROM_POSTGRES_ONLY:-false}'
      LANGFUSE_READ_FROM_CLICKHOUSE_ONLY: '${LANGFUSE_READ_FROM_CLICKHOUSE_ONLY:-true}'
      LANGFUSE_RETURN_FROM_CLICKHOUSE: '${LANGFUSE_RETURN_FROM_CLICKHOUSE:-true}'
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - 'langfuse_clickhouse_data:/var/lib/clickhouse'
      - 'langfuse_clickhouse_logs:/var/log/clickhouse-server'
    ports:
      - '8123:8123'
      - '9000:9000'
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1'
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
  minio:
    image: minio/minio
    restart: always
    container_name: minio
    entrypoint: sh
    command: '-c ''mkdir -p /data/langfuse && minio server --address ":9000" --console-address ":9001" /data'''
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    ports:
      - '9090:9000'
      - '9091:9001'
    volumes:
      - 'langfuse_minio_data:/data'
    healthcheck:
      test:
        - CMD
        - mc
        - ready
        - local
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
  redis:
    image: 'redis:7'
    restart: always
    command: "--requirepass ${REDIS_AUTH:-myredissecret}\n"
    ports:
      - '6379:6379'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 3s
      timeout: 10s
      retries: 10
volumes:
  langfuse_clickhouse_data:
    driver: local
  langfuse_clickhouse_logs:
    driver: local
  langfuse_minio_data:
    driver: local
```
