### DISCUSSION TITLE
Dynamic Project Management in LangFuse

### DISCUSSION THREAD

**Discussion by daniyalsaif200** [langfuse/langfuse#4945] [Support]
My use case is simple, I have two projects running, I'm using LiteLLM proxy and a simple chat completion AI app, LiteLLM is responsible for tracking on Langfuse. I want to implement dynamic project based tracking not specifying langfuse project keys in env/config file but rather some way dynamically.

I want that based on keys provided automatically the reflections should be shown to that project on langfuse as there will be mutliple projects/organization. I also do not want to use team logging in litellm because that again allows specifying projects.

Any help to this regard will really help, a way for dynamic project management based on API or in LiteLLM config.

Another issue is that right now we have to create secret key and public key as well is there a way we can generate only one project key for usage?

Litellm Config file
```
model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/BASE_URL/v1

litellm_settings:
  success_callback: ["langfuse"]
  turn_off_message_logging: false
```

@marcklingen
