### DISCUSSION TITLE
Bug ? can connect with REDIS_CONNECTION_STRING works but not when setting REDIS_(HOST|REDIS_PORT|REDIS_AUTH)

### DISCUSSION THREAD

**Discussion by bmm-alc** [langfuse/langfuse#5401] [Support] [answered]
Hello,

I working to build a helm configuration to deploy langfuse, until now I was using REDIS_CONNECTION_STRING that require to set password as cleartext
```
- name: "REDIS_CONNECTION_STRING"
  value: "redis://default:My$p4ss@langfuse-langfuse-valkey-primary:6379/0"
```
Now I use this as specified in the [documentation](https://langfuse.com/self-hosting/configuration) 
```
- name: "REDIS_HOST"
  value: langfuse-langfuse-valkey-primary
- name: "REDIS_PORT"
  value: "6379"
- name: "REDIS_AUTH"
  valueFrom:
    secretKeyRef:
      name: valkey-langfuse
      key: password
```
but the connection does not work.
as first sight I can see there is no variable for user in the code, neither the `/0` part at the end of the URL.

any idea ?
