### DISCUSSION TITLE
Setting up lang-fuse docker

### DISCUSSION THREAD

**Discussion by Vidit-Ostwal** [langfuse/langfuse#5423] [Support] [answered]
I am trying to setup langfuse via docker `docker compose up`

as stated in https://langfuse.com/self-hosting/local

The problem is the port 9000 on which both clickhouse and minio listens is already used up by a different system process which can not be killed.

I tired to change this, but I believe internally somewhere else also 9000 port is used.

```
No pending migrations to apply.
langfuse-web-1     | error: failed to open database: [hello] unexpected packet [72] from server in line 0: SHOW TABLES FROM "default" LIKE 'schema_migrations'
langfuse-web-1     | Applying clickhouse migrations failed. This is mostly caused by the database being unavailable.
langfuse-web-1     | Exiting...
```

Can some one tell, or know where all the port changes needs to be done. To make this work.

**Comment by dosubot** [comment]
Hey there, @Vidit-Ostwal! I'm here to help you with your Langfuse Docker setup hiccup 😊 Let's squash this bug together! 🐞


To resolve the port conflict issue with ClickHouse and MinIO in your Langfuse Docker setup, you need to update all instances where port 9000 is used. Here are the steps you should follow:

1. **ClickHouse Service:**
   - Change the port mapping from `"9000:9000"` to a different host port, for example: `"9001:9000"`.

2. **MinIO Service:**
   - Update the command to use a different port, for example: `--address ":9002"`.

3. **Environment Variables:**
   - Update `CLICKHOUSE_MIGRATION_URL` to reflect the new port, for example: `clickhouse://clickhouse:9001`.
   - Update `LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT` to reflect the new port, for example: `http://minio:9002`.

Here is an example of how your `docker-compose.yml` might look after these changes:

```yaml
clickhouse:
  ports:
    - "8123:8123"
    - "9001:9000"  # Updated host port

minio:
  command: -c 'mkdir -p /data/langfuse && minio server --address ":9002" --console-address ":9001" /data'  # Updated MinIO port

environment:
  CLICKHOUSE_MIGRATION_URL: ${CLICKHOUSE_MIGRATION_URL:-clickhouse://clickhouse:9001}  # Updated ClickHouse URL
  LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: ${LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT:-http://minio:9002}  # Updated MinIO endpoint
```

Make sure to update any other configurations or scripts that might reference these ports to ensure consistency across your setup. After making these changes, restart your containers with `docker compose up` <sup>[[1]](https://github.com/langfuse/langfuse/blob/main/docker-compose.dev.yml)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/eab12ff6-9d15-4cb9-888d-001873d1f055?feedback_type=other)</sup>
