### DISCUSSION TITLE
Changing default user and password for Redis results in WRONGPASS error

### DISCUSSION THREAD

**Discussion by rodrigobdz** [langfuse/langfuse#5443] [Support] [answered]
## Default configuration

According to the [docs](https://langfuse.com/self-hosting/infrastructure/cache), the default Redis connection string is as follows:

```sh
REDIS_CONNECTION_STRING=redis://default:changeme@<chart-name>-valkey-master:6379/0
```

## Custom configuration

The password `changeme` leads to the impression that it can be changed arbitrarily in the connection string. 
Example:

```sh
REDIS_CONNECTION_STRING=redis://default:CUSTOMPASSWORD@<chart-name>-valkey-master:6379/0
```

## Error

However, using a non-default `REDIS_CONNECTION_STRING` leads to the error in the `langfuse-worker` (Kubernetes deployment):

> ReplyError: WRONGPASS invalid username-password pair or user is disabled.

## Question

How to set a non-default username and password for Redis (especially in a Kubernetes deployment)?

**Comment by dosubot** [comment]
Hey @rodrigobdz! 👋 I'm here to help you out with any bugs, questions, or contributions you have while waiting for a human maintainer.


To set a non-default username and password for Redis in a Kubernetes deployment without encountering the WRONGPASS error, you need to ensure that the credentials in your configuration match those used by Redis. Here's how you can do it:

1. **Configure Redis with a Custom Password:**
   Update your `values.yaml` file for Redis to include your custom password:

   ```yaml
   valkey:
     deploy: true
     architecture: standalone
     primary:
       extraFlags:
         - "--maxmemory-policy noeviction" # Necessary to handle queue jobs correctly
     auth:
       password: yourpassword
   ```

2. **Set the Environment Variable:**
   Use the following environment variable to connect to your Redis instance with the custom password:

   ```bash
   REDIS_CONNECTION_STRING=redis://default:yourpassword@<chart-name>-valkey-master:6379/0
   ```

   Ensure that the password in the `auth` section of your `values.yaml` file matches the password in the `REDIS_CONNECTION_STRING`.

3. **Alternative Configuration:**
   Alternatively, you can use separate environment variables to configure your connection:

   ```bash
   REDIS_HOST=<chart-name>-valkey-master
   REDIS_PORT=6379
   REDIS_AUTH=yourpassword
   ```

Make sure the `maxmemory-policy` is set to `noeviction` to handle queue jobs correctly, as recommended in the Langfuse documentation <sup>[[1]](https://langfuse.com/docs/deployment/v3/components/redis)</sup><sup>[[2]](https://langfuse.com/self-hosting/infrastructure/cache)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/16085171-11e1-4d11-a5df-70317fbadec8?feedback_type=other)</sup>

**Reply by rodrigobdz** [reply]
The following only sets a custom password, but where do you set a custom username for Redis?

```yaml
valkey:
  deploy: true
  architecture: standalone
  primary:
    extraFlags:
      - "--maxmemory-policy noeviction" # Necessary to handle queue jobs correctly
  auth:
    password: yourpassword
```
