### DISCUSSION TITLE
Langfuse Docker Container Exits with “failed to parse scheme from database URL: no scheme” Despite Correct Environment Variables

### DISCUSSION THREAD

**Discussion by ianjohnsa** [langfuse/langfuse#5576] [Support] [answered]
Hello,

I’m running Langfuse in a multi‑container Docker Compose stack on Windows 10 (using WSL2), which also includes Open WebUI, SearXNG, Caddy, Redis, PostgreSQL, and ClickHouse. My goal is to have Langfuse integrate into our stack, and I’ve set the following environment variables in my docker‑compose file:

    LANGFUSE_API_KEY: (my Langfuse secret key)
    DATABASE_URL: "postgresql://langfuse:password123@langfuse_postgres:5432/langfuse"
    CLICKHOUSE_URL: "clickhouse://default:password123@langfuse_clickhouse:9000/default"

Here’s my intended Langfuse service configuration (as part of the docker‑compose yaml):

```
langfuse:
  image: ghcr.io/langfuse/langfuse:latest
  container_name: langfuse
  ports:
    - "3001:3000"
  volumes:
    - langfuse-data:/app/data
  environment:
    LANGFUSE_API_KEY: "sk-key-here"
    DATABASE_URL: "postgresql://langfuse:password123@langfuse_postgres:5432/langfuse"
    CLICKHOUSE_URL: "clickhouse://default:password123@langfuse_clickhouse:9000/default"
```

Issue:
When I start the stack with docker-compose up -d, the Langfuse container immediately exits. The logs (without any debug override) show the error:

```
error: failed to parse scheme from database URL: no scheme
Applying clickhouse migrations failed. This is mostly caused by the database being unavailable.
Exiting...
```

I’ve verified via docker-compose config that the environment variables are set as expected. I also inspected the persistent volume (langfuse-data) and found it to be empty—so there are no legacy config files that could be overriding my settings.

Debugging Steps Taken:
To troubleshoot further, I temporarily modified the Langfuse service in my docker‑compose file to override the entrypoint and command, preventing it from running its startup script immediately. My temporary configuration was as follows:

```
langfuse:
  image: ghcr.io/langfuse/langfuse:latest
  container_name: langfuse
  entrypoint: ["/bin/sh", "-c"]
  command: "tail -f /dev/null"
  ports:
    - "3001:3000"
  volumes:
    - langfuse-data:/app/data
  environment:
    LANGFUSE_API_KEY: "sk-yourkey"
    DATABASE_URL: "postgresql://langfuse:password123@langfuse_postgres:5432/langfuse"
    CLICKHOUSE_URL: "clickhouse://default:password123@langfuse_clickhouse:9000/default"
```

I did this to keep the container running so I could inspect its environment (via commands like env | grep -i URL) and verify that the variables are passed correctly. However, even with this override, the container still exits almost immediately with the same error once it attempts to run the startup script.

I’ve also tried running the image directly with an overridden entrypoint using a docker run command, but encountered issues with my shell (PowerShell parsing errors) and still couldn’t keep the container running long enough for inspection.

PostgreSQL and ClickHouse containers are running and configured as expected.
The langfuse-data volume is empty, so there are no old configuration files overriding my variables.
I’m using the latest Langfuse image from ghcr.io/langfuse/langfuse:latest.

I’m stuck because it appears that Langfuse’s startup script isn’t recognizing the provided environment variables—even though they are formatted correctly and visible in the effective configuration. Has anyone experienced this issue or have suggestions on how to ensure the environment variables are correctly picked up by Langfuse? Any help in troubleshooting this behavior would be greatly appreciated.
