### DISCUSSION TITLE
Clickhouse storage growing indefinitely?

### DISCUSSION THREAD

**Discussion by Pratish315** [langfuse/langfuse#5687] [Support] [answered]
Hi there,

I have deployed Langfuse on EKS using the official Helm chart. I have used RDS Postgres and ElastiCache for Redis. I am using EFS for Zookeeper's and Clickhouse's storage. 

I only have 5 traces and I am noticing that the EFS has grown from 300MB to 800MB without adding additional traces within the span of +-5 hours. It has also decreased slightly during these hours but continues to increase overall. 

I saw that we can control the TTL for the tables and I'll give that a try.

1. What is a rough estimate of the storage requirements for Clickhouse based on the number of traces?
2. Will the storage size of Clickhouse keep growing forever regardless if any traces are added or not?

**Comment by dosubot** [comment]
Hey @Pratish315! I'm here to help you with any bugs, questions, or contributions you have. Let's squash those bugs together!


1. Estimating the storage requirements for Clickhouse based on the number of traces can be challenging, as it depends on various factors such as the size and complexity of each trace, the number of observations and scores associated with them, and the configuration of your Clickhouse instance. However, Clickhouse is optimized for high write throughput and fast analytical queries, which can lead to rapid storage growth, especially if not managed properly <sup>[[1]](https://github.com/orgs/langfuse/discussions/5377)</sup>.

2. The storage size of Clickhouse can continue to grow if data retention and cleanup mechanisms are not properly configured. Langfuse provides a data retention processing job that can delete records older than a specified retention period, helping to manage storage size <sup>[[2]](https://github.com/langfuse/langfuse/blob/main/worker/src/__tests__/dataRetentionProcessing.test.ts)</sup>. Additionally, the `processClickhouseTraceDelete` function can be used to delete traces and associated data, which helps in managing storage size <sup>[[3]](https://github.com/langfuse/langfuse/blob/main/worker/src/features/traces/processClickhouseTraceDelete.ts)</sup>. Configuring these mechanisms can prevent indefinite storage growth.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/61d220a4-60be-4413-b484-1b042b693d17?feedback_type=other)</sup>

**Comment by Pratish315** [comment]
Hi @marcklingen, @Steffen911 , I hope you are well. 

Can I please get some insight on this issue? 

Its 2 days later and I still only have a single trace and my clickhouse EFS storage has grown from 400MB to 1.2GB. If this trend persists I might have to revert back to Langfuse V2 - which is a shame as we would like to be on the latest version of Langfuse.

We have grown fond of Langfuse and are trying to get Langfuse approved as enterprise standard with in our company, please can we get some assistance on this matter?

**Reply by Steffen911** [reply]
Hey @Pratish315 ,
We cannot give specific guidance on the storage behaviour of ClickHouse as it heavily depends on the workload and the traces you send to it. An option to keep the EFS disk size smaller is to use an S3 disk (https://clickhouse.com/docs/operations/storing-data). That way, the data lives in S3 and only metadata is kept in EFS which should be a more stable and smaller amount.

In https://github.com/langfuse/langfuse/issues/4893#issuecomment-2574833425 I created an example that uses Azure Blob Store as a disk and something fairly similar should work for S3 based on the documentation above.

**Reply by Pratish315** [reply]
Thanks @Steffen911 for the swift reply. 

I will try to look into using S3 for storage - thanks - but would it not result in the same issue where the size on S3 would just keep growing regardless if new traces are logged or not?

You mention that it heavily depends on the workload and the amount of traces - I currently only have 5 traces stored in Langfuse, its been that way since I first deployed it (2 days ago), I have not added more traces to it since then. Back when I first deployed it it was sitting around 400MB and now 2 days later its 1.2GB. 

Why is the storage constantly growing even though I am not adding new traces in?

**Comment by Pratish315** [comment, marked as answer]
**Solution Found: Optimizing ClickHouse Storage Usage**

I've discovered an effective solution to the indefinite storage growth issue with ClickHouse. The root cause appears to be related to the combined usage of ClickHouse with ZooKeeper, which was consuming excessive storage resources.


### **Implemented Changes**

1.) Removed ZooKeeper dependency: Switched to using ClickHouse's native Keeper functionality instead.
2.) Added storage optimization configuration:

```
<clickhouse>
    <profiles>
        <default>
            <log_queries>0</log_queries>
            <log_query_threads>0</log_query_threads>
        </default>
    </profiles>    
    <asynchronous_metric_log remove="1"/>
    <backup_log remove="1"/>
    <error_log remove="1"/>
    <metric_log remove="1"/>
    <query_thread_log remove="1" />  
    <query_log remove="1" />
    <query_views_log remove="1" />
    <part_log remove="1"/>
    <session_log remove="1"/>
    <text_log remove="1" />
    <trace_log remove="1"/>
    <crash_log remove="1"/>
    <opentelemetry_span_log remove="1"/>
    <zookeeper_log remove="1"/>
    <processors_profile_log remove="1"/>
</clickhouse>
```
Results
The improvements have been significant:

Before: With only 6 traces stored, EFS storage exceeded 600MB within 12 hours of installation
After: With the same 6 traces, EFS storage is now only 10MB after 12 hours

Although I'm still observing a slight growth trend, the reduction in storage consumption is dramatic enough to consider this issue resolved. We'll continue monitoring the system over time to ensure stability.
Note: For debugging purposes, it may be beneficial to keep log_queries enabled in production environments.

**Reply by charlie-liner** [reply]
Hi i am using helm and how can i modify clickhouse config?

**Reply by chenmi319** [reply]
> Hi i am using helm and how can i modify clickhouse config?

Now langfuse use chart version < 9.x(find from [here](https://github.com/langfuse/langfuse-k8s/blob/main/charts/langfuse/Chart.yaml)), use this config
```
clickhouse:
  extraOverrides: |
      <yandex>
        <trace_log remove="1"/>
        <text_log remove="1"/>
        <opentelemetry_span_log remove="1"/>
        <query_log remove="1"/>
        <processors_profile_log remove="1"/>
        <metric_log remove="1"/>
        <part_log remove="1"/>
        <asynchronous_metric_log remove="1"/>
        <query_views_log remove="1"/>
        <asynchronous_insert_log remove="1"/>
        <latency_log remove="1"/>
        <query_metric_log remove="1"/>
        <error_log remove="1"/>
      </yandex>
```

If langfuse upgrade clickhouse chart version >= 9.x, this may help
```
clickhouse:
  configdFiles:
    disable-system-logs.xml: |
      <yandex>
        <trace_log remove="1"/>
        <text_log remove="1"/>
        <opentelemetry_span_log remove="1"/>
        <query_log remove="1"/>
        <processors_profile_log remove="1"/>
        <metric_log remove="1"/>
        <part_log remove="1"/>
        <asynchronous_metric_log remove="1"/>
        <query_views_log remove="1"/>
        <asynchronous_insert_log remove="1"/>
        <latency_log remove="1"/>
        <query_metric_log remove="1"/>
        <error_log remove="1"/>
      </yandex>
```

**Reply by charlie-liner** [reply]
Thanks to reply! @chenmi319

**Reply by mfournioux** [reply]
Hello @chenmi319, how you configure the values in the helm chart to remove ZooKeeper dependency in order to switch to using ClickHouse's native Keeper functionality instead ?

**Reply by chenmi319** [reply]
> Hello @chenmi319, how you configure the values in the helm chart to remove ZooKeeper dependency in order to switch to using ClickHouse's native Keeper functionality instead ?

I disable zookeeper in clickhouse config  for a simple deployment...
```yaml
clickhouse:
  extraOverrides: |
      <yandex>
        <!-- 彻底禁用占空间大的 system 日志表 -->
        <trace_log remove="1"/>
        <text_log remove="1"/>
        <opentelemetry_span_log remove="1"/>
        <query_log remove="1"/>
        <processors_profile_log remove="1"/>
        <metric_log remove="1"/>
        <part_log remove="1"/>
        <asynchronous_metric_log remove="1"/>
        <query_views_log remove="1"/>
        <asynchronous_insert_log remove="1"/>
        <latency_log remove="1"/>
        <query_metric_log remove="1"/>
        <error_log remove="1"/>
      </yandex>
  auth:
    existingSecret: langfuse
    existingSecretKey: clickhouse-password
  image:
    repository: common/bitnami-clickhouse
    tag: 25.2.1-debian-12-r0
  zookeeper:
    enabled: false
    # image:
    #   repository: common/bitnami-zookeeper
    #   tag: 3.9.3-debian-12-r8
    # resources:
    #   requests:
    #     cpu: "1.5"
    #     memory: "2Gi"

  #  # 单分片
  shards: 1
  # 每个分片仅一份副本
  replicaCount: 1
  resources:
    requests:
      cpu: "1.5"
      memory: "4Gi"

```
