### DISCUSSION TITLE
Self-hosted Langfuse V3 just removed the database

### DISCUSSION THREAD

**Discussion by timurkhakhalev** [langfuse/langfuse#5802] [Support] [answered]
Hi there! I use [this docker compose ](https://github.com/langfuse/langfuse/blob/main/docker-compose.yml) as the base compose for the self-hosted langfuse.

I faced with the issue that langfuse suddenly removes its database from the postgres. How it's even possible and why?

Here is the part of configs:

```yaml
lf-postgres:
    image: postgres:${POSTGRES_VERSION:-latest}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lf-postgres
      POSTGRES_DB: langfuse
    ports:
      - 5432:5432
    volumes:
      - langfuse_postgres_data:/var/lib/postgresql/data
```

```.env
DATABASE_URL="postgresql://postgres:postgres@lf-postgres:5432/langfuse"
```

```
d exec -it e20 psql -V
psql (PostgreSQL) 17.4 (Debian 17.4-1.pgdg120+2)
```
