### DISCUSSION TITLE
S3 uploads InvalidAccessKeyId error

### DISCUSSION THREAD

**Discussion by dryearth** [langfuse/langfuse#5827] [Support] [answered]
I'm using version 1.0.0-rc.2.

Here are all my s3 related config(no additional config in additionEnvs):
```
s3:
  eventUpload:
    bucket: "mybucket"
    prefix: "langfuse/"
    region: "myregion"
    accessKeyId:
      value: "mykeyId"
    secretAccessKey:
      value: "myKey"
    ventUpload:
      prefix: "events/"
    batchExport:
      prefix: "exports/"
    mediaUpload:
      prefix: "media/"
```

I got this error in web pod:

```
2025-03-03T22:32:12.243Z error 	Failed to upload JSON to S3 langfuse/cm7f9r7tu0006zm06vu8bkdjw/observation/0a77aafe-7daf-47f5-8888-47d9f9830329/57296e6b-447b-4d86-8aaa-69a35b6f6583.json The Access Key Id you provided does not exist in our records.
InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.
    at throwDefaultError (/app/web/.next/server/chunks/8700.js:2435:14745)
    at /app/web/.next/server/chunks/8700.js:2435:14931
    at de_CommandError (/app/web/.next/server/chunks/8700.js:1:430619)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

I've verified my Id and Key are present in AWS, and my user have full s3 access.

What's wrong with my setup?

**Comment by dosubot** [comment]
The "InvalidAccessKeyId" error typically indicates that the access key ID provided does not match any existing keys in AWS. Here are a few things you can check to troubleshoot this issue:

1. **Verify Access Key and Secret**: Double-check that the `accessKeyId` and `secretAccessKey` values in your configuration are correct and match the credentials in your AWS account.

2. **Environment Variables**: Ensure that there are no environment variables or additional configurations that might be overriding the access key and secret in your setup.

3. **IAM User Permissions**: Confirm that the IAM user associated with the access key has the necessary permissions for S3 operations, such as `s3:PutObject`, `s3:ListBucket`, and `s3:GetObject`.

4. **Region Configuration**: Make sure that the region specified in your configuration matches the region where your S3 bucket is located.

5. **Configuration Structure**: Review your configuration structure to ensure there are no typos or misconfigurations. For example, ensure that the indentation and keys are correctly set.

6. **AWS Account**: Verify that the access key ID is associated with the correct AWS account, especially if you have multiple accounts.

If all these checks are correct and the issue persists, consider regenerating the access key and secret to ensure they are valid. Additionally, ensure that there are no network issues or restrictions that might be affecting the connection to AWS.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/9faf4884-bfb6-4874-85c6-1b5fc80249ae?feedback_type=other)</sup>

**Reply by marcklingen** [reply]
@dryearth did this resolve your question?

**Reply by Prateek057** [reply]
I am having the same issue, I have copied everything including AWS_SESSION_TOKEN to the container and I am still facing this issue: 
```
langfuse-server  | InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.
langfuse-server  |     at throwDefaultError (/app/web/.next/server/chunks/8700.js:2435:14745)
langfuse-server  |     at /app/web/.next/server/chunks/8700.js:2435:14931
langfuse-server  |     at de_CommandError (/app/web/.next/server/chunks/8700.js:1:430619)
langfuse-server  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:2424:39294
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:44:47780
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:2424:36992
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:44:31889
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:44:41459
langfuse-server  |     at async /app/web/.next/server/chunks/8700.js:44:41866
langfuse-server  | 2025-03-04T22:54:37.433Z error 	Failed to upload event to S3
langfuse-server  | 2025-03-04T22:54:37.434Z error 	error_handling_ingestion_event Failed to upload events to blob storage, aborting event processing
```

My Docker: Settings look like this: 

```
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:3.28.1
    container_name: langfuse-server
    depends_on:
      - langfuse-db
      - clickhouse
    ports:
      - "3001:3001"
      - "3030:3030"
    env_file:
      - .env
    environment:
      - PORT=3001/3030
      - NODE_ENV=development
      - DATABASE_URL=postgresql://${LANGFUSE_DB_USER}:${LANGFUSE_DB_PASSWORD}@langfuse-db:5433/${LANGFUSE_DB}
      - CLICKHOUSE_URL=http://@clickhouse:8123
      - CLICKHOUSE_MIGRATION_URL=clickhouse://@clickhouse:9000
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-clickhouse}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD:-clickhouse}
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=${LANGFUSE_PUBLIC_URL}
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - AWS_PROFILE=${AWS_DEFAULT_PROFILE:-default}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN:-""}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=${AWS_DEFAULT_REGION:-"eu-central-1"}
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=${LANGFUSE_S3_EVENT_UPLOAD_BUCKET}
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider", "http://langfuse-server:3000/api/public/health/"  ]
      interval: 30s
      timeout: 10s
      retries: 3
  ```
