### DISCUSSION TITLE
Batch export configuration missing in docker-compose.yml

### DISCUSSION THREAD

**Discussion by haobin-ihealth** [langfuse/langfuse#6197] [Support] [answered]
Hello,
I started the langfuse service through the docker compose file. When I tried to export traces, I saw the error "Batch export is not enabled." in the log. By consulting the documentation, I configured the S3 related configuration in the .env file and restarted docker. The error still persisted. I entered docker and found that my configured environment variables did not take effect. Then I checked the docker-compose.yml file and found that the LANGFUSE_S3_BATCH_EXPOR related environment variables were not imported in the langfuse-worker image. I added it manually and the error disappeared. I hope to add them in the docker-compose.yml file.
BR,

**Comment by dosubot** [comment]
Hey @haobin-ihealth! 👋 I'm here to help you out with any bugs, questions, or contributions you need assistance with. Let's squash those bugs together!


I found a similar solved discussion regarding the "Batch export is not enabled" error. The solution involved ensuring that the `LANGFUSE_S3_BATCH_EXPORT` environment variables are correctly configured and imported in the `langfuse-worker` image within the `docker-compose.yml` file. Here is an example configuration you can use:

```yaml
services:
  langfuse-worker:
    image: your-langfuse-worker-image
    environment:
      - LANGFUSE_S3_BATCH_EXPORT_ENABLED=true
      - LANGFUSE_S3_BATCH_EXPORT_BUCKET=your-batch-export-bucket-name
      - LANGFUSE_S3_BATCH_EXPORT_ACCESS_KEY_ID=your-access-key-id
      - LANGFUSE_S3_BATCH_EXPORT_SECRET_ACCESS_KEY=your-secret-access-key
      # Optional configurations
      - LANGFUSE_S3_BATCH_EXPORT_REGION=your-region
      - LANGFUSE_S3_BATCH_EXPORT_ENDPOINT=your-endpoint
      - LANGFUSE_S3_BATCH_EXPORT_FORCE_PATH_STYLE=true
      - LANGFUSE_S3_BATCH_EXPORT_PREFIX=your-prefix/
      - LANGFUSE_S3_BATCH_EXPORT_EXTERNAL_ENDPOINT=your-external-endpoint
```

Make sure to replace placeholders with your actual S3 credentials and bucket details. Setting `LANGFUSE_S3_BATCH_EXPORT_ENABLED` to `"true"` is crucial as it defaults to `"false"` <sup>[[1]](https://github.com/langfuse/langfuse/issues/5138)</sup>.



*To continue talking to [Dosu](https://dosu.dev), mention @dosu.*

---
<sup>Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=hallucination) | [Bug Report](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=bug_report) | [Other](https://app.dosu.dev/response-feedback/95a75312-e904-40b8-9343-57b298333496?feedback_type=other)</sup>
