### DISCUSSION TITLE
Using an OpenTelemetry Collector as a “middle‑man” to filter spans from `CallbackHandler` before they hit Langfuse

### DISCUSSION THREAD

**Discussion by jhrudden** [langfuse/langfuse#6554] [Support]
Heyo, I am sending traces to Langfuse with `langfuse.callback.CallbackHandler`, but we’d like to run them **through a local OpenTelemetry Collector first** so we can drop a few noisy spans (e.g., `__write__`) before they reach Langfuse.

My idea:

1. set `host` to `http://otel‑collector:4317` (otel instance in docker compose) in the CallbackHandler to route traffic to the collector instead of straight to `https://<tenant>.langfuse.com/api/public/otel`.
2. Collector uses the **`filterprocessor`** (or `attributesprocessor`) to exclude spans by name/attribute, then forwards the rest to Langfuse’s OTLP endpoint. 
3. Auth headers are passed unchanged in the OTLP exporter to Langfuse.

We can get traces into Langfuse directly, but with the collector in the middle we haven’t yet managed to see anything arrive (looks like the spans are dropped or mis‑routed).  

Has anyone already done this and uncovered any quirks—collector config, auth, or span resource attributes—that we should watch for?

Thanks for any nuance or sample configs! 🙏

**Comment by dosubot** [comment]
Hey @jhrudden! 👋 I'm here to help you tackle those pesky issues while you wait for a human maintainer. If you have any questions or need assistance with your OpenTelemetry setup, feel free to ask!


To filter spans from `CallbackHandler` using an OpenTelemetry Collector before they reach Langfuse, you can configure the collector with a `filterprocessor` to exclude specific spans by name or attribute. Here's a sample configuration that might help:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  filter/callbackhandler:
    error_mode: ignore
    traces:
      span:
        - 'name != "__write__"'  # Example of filtering out a noisy span

exporters:
  otlphttp/langfuse:
    endpoint: "https://cloud.langfuse.com/api/public/otel"  # EU data region
    # endpoint: "https://us.cloud.langfuse.com/api/public/otel"  # US data region
    headers:
      Authorization: "Basic ${AUTH_STRING}"  # Use your encoded API keys

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [filter/callbackhandler]
      exporters: [otlphttp/langfuse]
```

Make sure to set the `host` in `CallbackHandler` to point to your local OpenTelemetry Collector (`http://otel-collector:4317`). Ensure that the authorization headers are correctly passed in the OTLP exporter configuration to Langfuse.

A common issue is incomplete traces if essential spans are filtered out. Ensure that a root span is sent to Langfuse to maintain trace integrity <sup>[[1]](https://langfuse.com/docs/opentelemetry/get-started)</sup><sup>[[2]](https://langfuse.com/docs/opentelemetry)</sup>.



*To reply, just mention [@dosu](https://go.dosu.dev/dosubot?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=reply-with-mention&utm_term=langfuse%2Flangfuse).*

---

Share context across your team and agents. Try [Dosu](https://dosu.dev?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-tagline&utm_term=langfuse%2Flangfuse).

[![Leave Feedback](https://img.shields.io/badge/Leave%20Feedback-555555?style=flat)](https://app.dosu.dev/response-feedback?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-feedback&utm_term=langfuse%2Flangfuse&message_id=92edf4df-812f-426d-82f6-49d578faafd2) [![Learn about langfuse with Dosu](https://img.shields.io/badge/Learn%20about%20langfuse%20with%20Dosu-2f7b3f?style=flat&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iODYiIGhlaWdodD0iODkiIHZpZXdCb3g9IjAgMCA4NiA4OSIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNS4yOTIzNiAxMi43OTI4TDE3Ljc1OTMgNi42ODE4OFY3Mi41NjY3TDUuMjkyMzYgODQuMDYxOFYxMi43OTI4WiIgZmlsbD0iI0I0QkI5MSIvPjxwYXRoIGQ9Ik0xOC4yNTc1IDczLjExOTZMNTkuMTMyOSA3Mi43NDhMNTEuNzAxMSA4Mi40MDk1TDI5LjAzMzggODYuMjkxTDYuMjM5NjIgODUuMTU1NEwxOC4yNTc1IDczLjExOTZaIiBmaWxsPSIjNzc4NTYxIi8%2BPHBhdGggZD0iTTE3LjQ5MTYgMy43MzYzM0wzLjU4NTU3IDEyLjcwOTlWODMuNTc5MkMzLjU4NTU3IDg0Ljc1NDIgNC45ODU2MyA4NS4zNjUyIDUuODQ3MDUgODQuNTY2TDE5LjYyOTYgNzEuNzgwMSIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjQyODQ0IiBzdHJva2UtbGluZWNhcD0icm91bmQiLz48bWFzayBpZD0iZG9zdS1kLWN1dG91dCIgZmlsbD0id2hpdGUiPjxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgY2xpcC1ydWxlPSJldmVub2RkIiBkPSJNNDAuNzA0IDAuNTE4MDY2SDE3LjA0MzlWNzYuMjIyMUg0MC43MDRINDIuNTgwNUg0Ny44MDEzQzY4LjcwNjQgNzYuMjIyMSA4NS42NTMzIDU5LjI3NTIgODUuNjUzMyAzOC4zNzAxQzg1LjY1MzMgMTcuNDY1IDY4LjcwNjMgMC41MTgwNjYgNDcuODAxMyAwLjUxODA2Nkg0Mi41ODA1SDQwLjcwNFoiLz48L21hc2s%2BPHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBjbGlwLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik00MC43MDQgMC41MTgwNjZIMTcuMDQzOVY3Ni4yMjIxSDQwLjcwNEg0Mi41ODA1SDQ3LjgwMTNDNjguNzA2NCA3Ni4yMjIxIDg1LjY1MzMgNTkuMjc1MiA4NS42NTMzIDM4LjM3MDFDODUuNjUzMyAxNy40NjUgNjguNzA2MyAwLjUxODA2NiA0Ny44MDEzIDAuNTE4MDY2SDQyLjU4MDVINDAuNzA0WiIgZmlsbD0iI0YzRjZGMSIvPjxwYXRoIGQ9Ik0xNy4wNDM5IDAuNTE4MDY2Vi02LjU3OTE5SDkuOTQ2NjlWMC41MTgwNjZIMTcuMDQzOVpNMTcuMDQzOSA3Ni4yMjIxSDkuOTQ2NjlWODMuMzE5NEgxNy4wNDM5Vjc2LjIyMjFaTTE3LjA0MzkgNy42MTUzMkg0MC43MDRWLTYuNTc5MTlIMTcuMDQzOVY3LjYxNTMyWk0yNC4xNDEyIDc2LjIyMjFWMC41MTgwNjZIOS45NDY2OVY3Ni4yMjIxSDI0LjE0MTJaTTQwLjcwNCA2OS4xMjQ5SDE3LjA0MzlWODMuMzE5NEg0MC43MDRWNjkuMTI0OVpNNDIuNTgwNSA2OS4xMjQ5SDQwLjcwNFY4My4zMTk0SDQyLjU4MDVWNjkuMTI0OVpNNDcuODAxMyA2OS4xMjQ5SDQyLjU4MDVWODMuMzE5NEg0Ny44MDEzVjY5LjEyNDlaTTc4LjU1NiAzOC4zNzAxQzc4LjU1NiA1NS4zNTU1IDY0Ljc4NjcgNjkuMTI0OSA0Ny44MDEzIDY5LjEyNDlWODMuMzE5NEM3Mi42MjYxIDgzLjMxOTQgOTIuNzUwNSA2My4xOTQ5IDkyLjc1MDUgMzguMzcwMUg3OC41NTZaTTQ3LjgwMTMgNy42MTUzMkM2NC43ODY2IDcuNjE1MzIgNzguNTU2IDIxLjM4NDcgNzguNTU2IDM4LjM3MDFIOTIuNzUwNUM5Mi43NTA1IDEzLjU0NTMgNzIuNjI2IC02LjU3OTE5IDQ3LjgwMTMgLTYuNTc5MTlWNy42MTUzMlpNNDIuNTgwNSA3LjYxNTMySDQ3LjgwMTNWLTYuNTc5MTlINDIuNTgwNVY3LjYxNTMyWk00MC43MDQgNy42MTUzMkg0Mi41ODA1Vi02LjU3OTE5SDQwLjcwNFY3LjYxNTMyWiIgZmlsbD0iYmxhY2siIG1hc2s9InVybCgjZG9zdS1kLWN1dG91dCkiLz48cGF0aCBkPSJNNjguOTIxNSAzNi4wMTM1QzY4LjkyMTUgMzYuMDEzNSA2NS43MzY5IDQ5LjQ3MzggNTEuNDIzMSA0OS40NzM4QzM3LjEwOTMgNDkuNDczOCAzMi41Nzg3IDM3LjM1OTYgMzIuNTc4NyAzNi4wMTM1IiBzdHJva2U9ImJsYWNrIiBzdHJva2Utd2lkdGg9IjcuNjkxNjEiIHN0cm9rZS1saW5lY2FwPSJyb3VuZCIgc3Ryb2tlLWxpbmVqb2luPSJyb3VuZCIvPjxwYXRoIGQ9Ik0wLjM0ODYzMyA4NS40OTQ2QzAuMzQ4NjMzIDg1LjQ5NDYgMjkuNDg1NiA4NS44MzA5IDM0LjgwOSA4NS42OThDNDQuODMzNyA4NS40NDc3IDUxLjI4NzIgODQuNDAyIDU3LjUyNjkgNzguOTcyNEM2Mi44MTI5IDc0LjM3MjcgNzUuMTM0MiA1OS42ODM2IDc1LjEzNDIgNTkuNjgzNiIgc3Ryb2tlPSJibGFjayIgc3Ryb2tlLXdpZHRoPSI2LjE2NDgyIi8%2BPC9zdmc%2B)](https://github.dosu.com/langfuse/langfuse?utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-learn-repo&utm_term=langfuse%2Flangfuse) [![Add Dosu to your team](https://img.shields.io/badge/Add%20Dosu%20to%20your%20team-1f6feb?style=flat)](https://app.dosu.dev/signup?referrer=openSource&source=github-footer&utm_source=github&utm_medium=bot-comment&utm_campaign=github-comment-footer-20260415&utm_content=knowledge-infrastructure-add-team&utm_term=langfuse%2Flangfuse)

**Reply by TheDCode** [reply]
@jhrudden Did you ever figure this out?

**Comment by jdbranham** [comment]
This works for me.
I've only done basic testing - so I'm not 100% certain it's filtering something I actually want, but you can tweak the filter.  

The `$LANGFUSE_OTEL_AUTH` is base64 encoded like this - `AUTH=$(echo -n "pk-lf-xxx:sk-lf-xxx" | base64)`

In my case, I wanted all the spans to go jaeger, but only LLM related spans to go to LangFuse

```
# OpenTelemetry Collector configuration for Kenobi-C2S
# This collector receives, processes, and exports telemetry data

receivers:
  # OTLP receiver for traces and metrics from the application
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Prometheus receiver to scrape metrics from the application
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8888"]

  # Host metrics receiver for system metrics
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:

  # Jaeger receiver for backward compatibility
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_http:
        endpoint: 0.0.0.0:14268
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_binary:
        endpoint: 0.0.0.0:6832

processors:
  # Batch processor to batch telemetry before sending
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  # Resource processor to add/modify resource attributes
  resource:
    attributes:
      - key: environment
        value: ${OTEL_ENVIRONMENT}
        action: upsert
      - key: service.namespace
        value: kenobi-c2s
        action: upsert
      - key: telemetry.sdk.name
        value: opentelemetry
        action: upsert

  # Span processor for trace data
  span:
    name:
      from_attributes: ["http.method", "http.route"]
      separator: " "

  # Metrics transform processor
  metricstransform:
    transforms:
      - include: http_server_duration
        match_type: regexp
        action: update
        new_name: http.server.duration
      - include: http_server_active_requests
        match_type: regexp
        action: update
        new_name: http.server.active_requests

  # Attributes processor to remove sensitive data
  attributes:
    actions:
      - key: http.request.header.authorization
        action: delete
      - key: http.request.header.x-api-key
        action: delete
      - key: db.statement
        action: update
        from_attribute: db.statement
        # Redact sensitive SQL data
      - key: http.request.header.cookie
        action: delete
      - key: http.response.header.set-cookie
        action: delete

  # Filter processor to drop unwanted telemetry
  filter:
    error_mode: ignore
    traces:
      span:
        # Drop health check traces to reduce noise
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/metrics"'
    metrics:
      metric:
        # Drop internal metrics if needed
        - 'name == "otelcol_process_uptime"'

  # Filter processor for LLM-only traces (for Langfuse pipeline)
  # This filter EXCLUDES non-LLM spans, keeping only LLM-related traces
  filter/llm_only:
    error_mode: ignore
    traces:
      span:
        # =============================================================================
        # EXCLUDE: Application middleware and instrumentation noise
        # =============================================================================
        # Catch-all: Exclude ANY span without openinference.span.kind that doesn't
        # match known LLM operation patterns. This prevents unknown noise from reaching Langfuse.
        - 'attributes["openinference.span.kind"] == nil and not IsMatch(name, "(?i).*(llm|openai|azureopenai|anthropic|claude|gpt|chat|completion|embedding|retriev|rerank|synthesi|query_engine|vector|index|agent|tool|workflow|llama|chunk|node|parse|extract|transform|generate|predict|invoke|call|run).*")'

        # =============================================================================
        # EXCLUDE: HTTP framework spans
        # =============================================================================
        - 'IsMatch(name, "(?i)^(GET|POST|PUT|DELETE|PATCH|HEAD|OPTIONS)\\s") and attributes["openinference.span.kind"] == nil'
        - 'IsMatch(name, "(?i)^(http\\s*(send|receive)|HTTP\\s*(send|receive))") and attributes["openinference.span.kind"] == nil'

        # =============================================================================
        # EXCLUDE: Database/SQL spans
        # =============================================================================
        - 'IsMatch(name, "(?i)^(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|TRUNCATE)\\s") and attributes["openinference.span.kind"] == nil'
        - 'attributes["db.system"] != nil and attributes["openinference.span.kind"] == nil'

        # =============================================================================
        # EXCLUDE: Framework internals and middleware
        # =============================================================================
        - 'IsMatch(name, "(?i)^(middleware|cors|exception|starlette|fastapi|asgi|uvicorn)") and attributes["openinference.span.kind"] == nil'

        # =============================================================================
        # EXCLUDE: Low-level operations
        # =============================================================================
        - 'IsMatch(name, "(?i)^(connect|read|write|close|send|receive|socket)$") and attributes["openinference.span.kind"] == nil'

        # =============================================================================
        # EXCLUDE: Health checks and metrics endpoints
        # =============================================================================
        - 'attributes["http.route"] == "/health"'
        - 'attributes["http.route"] == "/metrics"'
        - 'attributes["http.route"] == "/api/health"'
        - 'attributes["http.target"] == "/health"'

        # =============================================================================
        # EXCLUDE: Static files
        # =============================================================================
        - 'IsMatch(attributes["http.route"], "(?i)\\.(css|js|ico|png|jpg|svg|woff|ttf)$")'

        # =============================================================================
        # KEEP: LLM-related spans that pass all exclusions above
        # =============================================================================
        # - Spans with openinference.span.kind attribute (LlamaIndex/LangChain OpenInference)
        # - Spans with names containing LLM operation keywords

exporters:
  # OTLP/gRPC exporter to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Prometheus exporter for metrics
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      service: kenobi-c2s
    resource_to_telemetry_conversion:
      enabled: true
    enable_open_metrics: true

  # Logging exporter for debugging
  logging:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # OTLP/HTTP exporter for logs to Loki
  otlphttp/logs:
    endpoint: http://loki:3100/otlp
    tls:
      insecure: true

  # Langfuse OTLP/HTTP exporter for LLM traces
  # Langfuse accepts OTLP traces at /api/public/otel/v1/traces with Basic Auth
  otlphttp/langfuse:
    endpoint: $LANGFUSE_OTEL_ENDPOINT
    headers:
      Authorization: "Basic $LANGFUSE_OTEL_AUTH"
    tls:
      insecure: $LANGFUSE_TLS_INSECURE
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      num_consumers: 10
      queue_size: 5000
    timeout: 30s
  # File exporter for debugging (optional)
  # file:
  #   path: /tmp/otel-collector.json
  #   rotation:
  #     max_megabytes: 100
  #     max_days: 7
  #     max_backups: 3

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
    path: "/health"
    check_collector_pipeline:
      enabled: true
      interval: 10s
      exporter_failure_threshold: 5

  # Performance profiler
  pprof:
    endpoint: 0.0.0.0:1777

  # zPages for debugging
  zpages:
    endpoint: 0.0.0.0:55679

  # Memory ballast to improve GC performance
  memory_ballast:
    size_mib: 256

service:
  # Enable extensions
  extensions:
    - health_check
    - pprof
    - zpages
    - memory_ballast

  # Configure pipelines
  pipelines:
    # Main traces pipeline - all traces go to Jaeger
    traces:
      receivers: [otlp, jaeger]
      processors: [memory_limiter, resource, span, attributes, filter, batch]
      exporters: [otlp/jaeger, logging]

    # LLM traces pipeline - filtered LLM-only traces go to Langfuse
    # This pipeline receives the same OTLP input but filters to only LLM spans
    traces/langfuse:
      receivers: [otlp]
      processors: [memory_limiter, resource, filter/llm_only, batch]
      exporters: [otlphttp/langfuse]

    # Metrics pipeline
    metrics:
      receivers: [otlp, prometheus, hostmetrics]
      processors:
        [memory_limiter, resource, metricstransform, attributes, filter, batch]
      exporters: [prometheus, logging]

    # Logs pipeline (if needed)
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, attributes, batch]
      exporters: [otlphttp/logs, logging]

  # Telemetry configuration for the collector itself
  telemetry:
    logs:
      level: WARN
      initial_fields:
        service: otel-collector
    metrics:
      level: detailed
      address: 0.0.0.0:8888
```
