### DISCUSSION TITLE
Using env_file in Docker compose

### DISCUSSION THREAD

**Discussion by Spongillas** [langfuse/langfuse#6640] [Support]
Hello!

I use self-hosted Langfuse via docker-compose, all environmental variables are stored in .env.
I wanted to use this file by declarating env_file in docker compose for langfuse-web, but it doesn't work.
It works only if I directly declare variables in environment.

For example, I have variables in .env:
```
LANGFUSE_INIT_ORG_ID=UDV
LANGFUSE_INIT_ORG_NAME=UDV
LANGFUSE_INIT_PROJECT_ID=soc-digital-assistant
LANGFUSE_INIT_PROJECT_NAME=soc-digital-assistant
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf
LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf
LANGFUSE_INIT_USER_EMAIL=admin@admin.com
LANGFUSE_INIT_USER_NAME=admin
LANGFUSE_INIT_USER_PASSWORD=admin123
```

Docker compose doesn't create user:
```
  langfuse-web:
    image: langfuse/langfuse:3
    restart: always
    container_name: langfuse_web
    depends_on: *langfuse-depends-on
    env_file:
      - .env
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_URL: ${LANGFUSE_NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${LANGFUSE_NEXTAUTH_SECRET:-secret}
```

Docker compose succesfully create user:
```
  langfuse-web:
    image: langfuse/langfuse:3
    restart: always
    container_name: langfuse_web
    depends_on: *langfuse-depends-on
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_URL: ${LANGFUSE_NEXTAUTH_URL:-http://localhost:3000}
      NEXTAUTH_SECRET: ${LANGFUSE_NEXTAUTH_SECRET:-secret}
      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID}
      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME}
      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID}
      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME}
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY}
      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY}
      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL}
      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_NAME}
      LANGFUSE_INIT_USER_PASSWORD: ${LANGFUSE_INIT_USER_PASSWORD}
```

It's bug or my misunderstanding?
Thanks
