### DISCUSSION TITLE
Invalid credentials error when running langfuse & otel-collector locally

### DISCUSSION THREAD

**Discussion by egattoc** [langfuse/langfuse#7071] [Support] [answered]
@Steffen911 tagging you here like you requested, thanks in advance
I am running a local setup, with langfuse and otel-collector in docker containers. In my docker compose file, I've got all the langfuse-related containers as is from the repo, just changed some host port numbers. Specifically, this is what my langfuse-web container config looks like. I had created a project, API keys etc through the langfuse UI and then passed them here:

```
langfuse-web:
    image: langfuse/langfuse:3
    restart: always
    depends_on: *langfuse-depends-on
    ports:
      - 3010:3000
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_URL: http://localhost:3010
      NEXTAUTH_SECRET: mysecret # CHANGEME
      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID:-*********}
      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME:-test-org}
      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID:-*********}
      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME:-my-llm-project}
      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: pk-*********
      LANGFUSE_INIT_PROJECT_SECRET_KEY: sk-*********
      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL:-<my_email>}
      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_NAME:-<my_name>}
      LANGFUSE_INIT_USER_PASSWORD: ${LANGFUSE_INIT_USER_PASSWORD:-<my_password>}
```

In the same docker compose file, I've also added my otel-collector config:

```
otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"     
    restart: on-failure
```

This is what my otel-collector-config file looks like:

```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    send_batch_size: 100000
  memory_limiter:
    # 80% of maximum memory up to 2G
    limit_mib: 1500
    # 25% of limit up to 2G
    spike_limit_mib: 512
    check_interval: 5s

exporters:
  otlphttp/langfuse:
    # endpoint: "https://us.cloud.langfuse.com/api/public/otel" # US data region
    endpoint: "http://localhost:3010/api/public/otel"
    headers:
      Authorization: "Basic <base64 encoded pk:sk>" # Previously encoded API keys

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [otlphttp/langfuse]
```

However, when the stack is up and traces are generated, I see this error in the otel-collector logs:

`internal/retry_sender.go:133	Exporting failed. Will retry the request after interval.	{"resource": {}, "otelcol.component.id": "otlphttp/langfuse", "otelcol.component.kind": "exporter", "otelcol.signal": "traces", "error": "failed to make an HTTP request: Post \"http://localhost:3010/api/public/otel/v1/traces\": dial tcp [::1]:3010: connect: connection refused", "interval": "23.424926537s"}`

and this error in the `langfuse-web` container logs:

```
langfuse-web-1     | 2025-05-29T06:50:33.565Z error 	No key found for public key
langfuse-web-1     | 2025-05-29T06:50:33.577Z info 	No key found, storing api-key-non-existent in redis
langfuse-web-1     | 2025-05-29T06:50:33.577Z error 	Error verifying auth header: Invalid credentials Invalid credentials
langfuse-web-1     | Error: Invalid credentials
langfuse-web-1     |     at /app/web/.next/server/pages/api/public/ingestion.js:1:14658
langfuse-web-1     |     at async /app/web/.next/server/chunks/6018.js:1:84117
langfuse-web-1     |     at async u.verifyAuthHeaderAndReturnScope (/app/web/.next/server/pages/api/public/ingestion.js:1:13957)
langfuse-web-1     |     at async f (/app/web/.next/server/pages/api/public/ingestion.js:1:3602)
langfuse-web-1     |     at async /app/node_modules/.pnpm/@sentry+nextjs@8.55.0_@opentelemetry+context-async-hooks@1.30.1_@opentelemetry+api@1.9.0__@op_yxmnsh5q42byghexzhev4f2lue/node_modules/@sentry/nextjs/build/cjs/common/pages-router-instrumentation/wrapApiHandlerWithSentry.js:89:28
langfuse-web-1     |     at async K (/app/node_modules/.pnpm/next@14.2.26_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_ziavnkuctfn4jzwmsmu2grdr5u/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16881)
langfuse-web-1     |     at async U.render (/app/node_modules/.pnpm/next@14.2.26_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_ziavnkuctfn4jzwmsmu2grdr5u/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17520)
langfuse-web-1     |     at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@14.2.26_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_ziavnkuctfn4jzwmsmu2grdr5u/node_modules/next/dist/server/next-server.js:603:9)
langfuse-web-1     |     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.26_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_ziavnkuctfn4jzwmsmu2grdr5u/node_modules/next/dist/server/next-server.js:269:37)
langfuse-web-1     |     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.26_@babel+core@7.24.3_@opentelemetry+api@1.9.0_@playwright+test@1.47.2_babel-plugin_ziavnkuctfn4jzwmsmu2grdr5u/node_modules/next/dist/server/base-server.js:818:17)

```
