### ISSUE TITLE
bug: Invalid `prisma.user.findUnique()` invocation: The table `public.users` does not exist in the current database.

### ISSUE THREAD

**Issue by abnerjacobsen** [langfuse/langfuse#1108]
### Describe the bug

I have configure Langfuse DB URL's like this:

```
DIRECT_URL="postgresql://postgres:postgres@db:5432/langfuse"
DATABASE_URL="postgresql://postgres:postgres@db:5432/langfuse"
```

When I start the docker containers eith docker compose all the tables are created in the correct dataname, but, when I try to create the first user using the UI I got this error:

`Invalid `prisma.user.findUnique()` invocation: The table `public.users` does not exist in the current database.`

Langsuse can only work with a database named postgres or I'm doing anything wrong in my configuration ?

regards,

### To reproduce

Just change the DB URL's to use another database name.

### Additional information

My .env config is this:

```
# When adding additional environment variables, the schema in "/src/env.mjs"
# should be updated accordingly.

# Prisma
# https://www.prisma.io/docs/reference/database-reference/connection-urls#env
DIRECT_URL="postgresql://postgres:postgres@db:5432/langfuse"
DATABASE_URL="postgresql://postgres:postgres@db:5432/langfuse"

# Next Auth
# You can generate a new secret on the command line with:
# openssl rand -base64 32
# https://next-auth.js.org/configuration/options#secret
# NEXTAUTH_SECRET=""
NEXTAUTH_URL="http://localhost:3000"
NEXTAUTH_SECRET="ZXC6dI8sTRNtzBXRGzk9Px8McKXSptdriu5TM6+qITY="

# Langfuse experimental features
LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES="true"

# Salt for API key hashing
SALT="BlBGXZ4t3o9Oe8+7apsgPFGOWywTla8P8db1OXqSvPk="

# Email
EMAIL_FROM_ADDRESS=""  # Defines the email address to use as the from address.
SMTP_CONNECTION_URL=""  # Defines the connection url for smtp server.

# S3 storage
S3_ENDPOINT=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=
S3_REGION=

```

**Comment by marcklingen** [comment]
I think the issue here is that you use `.env` while running langfuse via `docker compose`. If you run Langfuse via docker compose, the environments are set in `docker-compose.yml`.

I've just tried to reproduce the issue and set an alternative db name in `docker-compose.yml` and it worked without any issues:.

```
version: "3.5"

services:
  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/langfuse
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=langfuse
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

Feel free to reopen if this doesn't fix the issue for you, happy to help.
