### ISSUE TITLE
bug: The latest image seems to have UI issue

### ISSUE THREAD

**Issue by hypernovas** [langfuse/langfuse#1549]
### Describe the bug

I upgrade from v2.14.6-0 to the latest (we try to test OKTA integration with this [PR ](https://github.com/langfuse/langfuse/pull/506/files)included), the frontend does not work:
Screenshot:
<img width="246" alt="Screenshot 2024-03-29 at 4 27 01 PM" src="https://github.com/langfuse/langfuse/assets/17284665/7dfb9b84-ca63-44da-b87d-d9654a1cda24">

The server log looks fine:
<img width="924" alt="Screenshot 2024-03-29 at 4 29 40 PM" src="https://github.com/langfuse/langfuse/assets/17284665/e3074e01-3383-4366-906b-b4ee830996b8">

### To reproduce

The kubernetes deployment yaml is the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: langfuse-deployment
  labels:
    app: langfuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langfuse
  template:
    metadata:
      labels:
        app: langfuse
    spec:
      containers:
      - name: langfuse-container
        image: ghcr.io/langfuse/langfuse:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@{our-aws-RDS-db}.us-west-2.rds.amazonaws.com:5432/langfuse"
        - name: NEXTAUTH_URL
          value: "http://{host_URL}:3000"
        - name: NEXTAUTH_SECRET
          value: "mysecret"
        - name: SALT
          value: "mysalt"
---
apiVersion: v1
kind: Service
metadata:
  name: langfuse-svc
spec:
  selector:
    app: langfuse
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
```
