### ISSUE TITLE
bug: LANGFUSE_DEFAULT_PROJECT_ID not working

### ISSUE THREAD

**Issue by scieneer-jonas** [langfuse/langfuse#2016]
### Describe the bug

The LANGFUSE_DEFAULT_PROJECT_ID does not seem to work. I tried a couple of names, but a new user account is always greeted with the "Get started - Create new project" page. Also tried to set LANGFUSE_DEFAULT_PROJECT_ROLE to 'ADMIN' at the same time, but without success. The default project defined in LANGFUSE_DEFAULT_PROJECT_ID does also not appear in the postgres projects table, like the other langfuse projects. 

I also tried starting with a fresh DB without any Langfuse projects and created the LANGFUSE_DEFAULT_PROJECT_ID manually, but new users also would not be added to this project.

See the docker compose file for recreation: 

### To reproduce

```yaml
version: "0.1"
name: langfuseexample
services:
  langfuse:
    image: langfuse/langfuse:2.38.0
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: 'postgres:5432'
      DATABASE_NAME: 'langfuse'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'tempP@ssw0rd'
      NEXTAUTH_SECRET: 'mysecret'
      SALT: 'mysalt'
      NEXTAUTH_URL: 'http://localhost:3000'
      LANGFUSE_DEFAULT_PROJECT_ID: test
      LANGFUSE_DEFAULT_PROJECT_ROLE: 'ADMIN'

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'tempP@ssw0rd'
      POSTGRES_USER: 'postgres'
      # default db name
      POSTGRES_DB: 'postgres'
```

### SDK and container versions

langfuse/langfuse:2.38.0

### Are you interested to contribute a fix for this bug?

No
