### ISSUE TITLE
[LFC-195] bug: need to refresh page when session changes (signup/login/logout), self-hosting

### ISSUE THREAD

**Issue by halyearzero** [langfuse/langfuse#226]
### Describe the bug

After starting self-hosted Langfuse, interaction with the signup/login mechanism hangs. Usually a refresh of the page will resolve the issue.

### To reproduce

Here's my docker compose file:

```
version: '3.8'
services:
  <other-service-A>:
    ...
  <other-service-B>:
    ...
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: xxxx
      POSTGRES_PASSWORD: xxxx
      POSTGRES_DB: xxxx
    ports:
      - "5432:5432"
    volumes:
      - ${HOME}/data/postgres:/var/lib/postgresql/data
    networks:
      - network1
  langfuse:
    image: ghcr.io/langfuse/langfuse:latest
    environment:
      DATABASE_URL: postgresql://xxxx:xxxx@postgres:5432/postgres
      NEXTAUTH_SECRET: mysecret
      NEXTAUTH_URL: http://XXX.XX.0.1:3002
    ports:
      - 3002:3000
    networks:
      - network1
networks:
  network1:
    name: my-network
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: XXX.XX.0.0/16
          ip_range: XXX.XX.5.0/24
          gateway: XXX.XX.0.1
```

### Additional information

Network

![image](https://github.com/langfuse/langfuse/assets/2834609/6bbd0ad8-a80f-4827-9c6c-33e0b881653f)

<sub>[LFC-195](https://linear.app/langfuse/issue/LFC-195/bug-need-to-refresh-page-when-session-changes-signuploginlogout-self)</sub>
