### ISSUE TITLE
bug: Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name.

### ISSUE THREAD

**Issue by BAEK26** [langfuse/langfuse#2726]
### Describe the bug

cannot disable the warning logs.
I don't want show this log:Langfuse was not able to parse the LLM model. The LLM call will be recorded without model name. Please create an issue so we can fix your integration.

How to turn off the logs?

### To reproduce

logging.basicConfig(level=100, format='%(message)s - %(asctime)s - %(name)s - %(levelname)s')
still I can show the message, whenever I call the query..

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
Which model do you use? Happy to just add support for the model in order to make these logs disappear

**Comment by BAEK26** [comment]
I am using llama3 (70B or 8B)
configs is below
```yaml
llm:
              max_retries: 1000000
              max_tokens: 1024
              model: llama3:70b-instruct-fp16
              platform: open_webui
              temperature: 0
              top_p: 1
```
