### ISSUE TITLE
bug: Invalid `prisma.datasetItem.findMany()` invocation: The column `t1.project_id` does not exist in the current database.

### ISSUE THREAD

**Issue by vatsal-kavida** [langfuse/langfuse#2930]
### Describe the bug

I am getting the given error message in my langfuse UI -> 
Invalid `prisma.datasetItem.findMany()` invocation: The column `t1.project_id` does not exist in the current database.
Path: datasets.datasetItemsBasedOnTraceOrObservation

I have deployed my langfuse using helm
 also when restarted now unable to sign in with the below error ->
 
```
The table `public.organization_memberships` does not exist in the current database.
[next-auth][error][JWT_SESSION_ERROR] 
https://next-auth.js.org/errors#jwt_session_error 
Invalid `prisma.user.findUnique()` invocation:

The table `public.organization_memberships` does not exist in the current database. {
  message: '\n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The table `public.organization_memberships` does not exist in the current database.',
  stack: 'PrismaClientKnownRequestError: \n' +
    'Invalid `prisma.user.findUnique()` invocation:\n' +
    '\n' +
    '\n' +
    'The table `public.organization_memberships` does not exist in the current database.\n' +
    '    at In.handleRequestError (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:6854)\n' +
    '    at In.handleAndLogRequestError (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:6188)\n' +
    '    at In.request (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:122:5896)\n' +
    '    at async l (/app/node_modules/.pnpm/@prisma+client@5.13.0_prisma@5.13.0/node_modules/@prisma/client/runtime/library.js:127:11167)\n' +
    '    at async Object.session (/app/web/.next/server/chunks/8889.js:1:8069)\n' +
    '    at async Object.session (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.7_@opentelemetry+api@1.9.0_@playwright+test@1.4_xsr6hv6cl6buuxt2dqdt6da6xu/node_modules/next-auth/core/routes/session.js:55:30)\n' +
    '    at async AuthHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.7_@opentelemetry+api@1.9.0_@playwright+test@1.4_xsr6hv6cl6buuxt2dqdt6da6xu/node_modules/next-auth/core/index.js:165:27)\n' +
    '    at async NextAuthApiHandler (/app/node_modules/.pnpm/next-auth@4.24.7_next@14.2.3_@babel+core@7.24.7_@opentelemetry+api@1.9.0_@playwright+test@1.4_xsr6hv6cl6buuxt2dqdt6da6xu/node_modules/next-auth/next/index.js:22:19)\n' +
    '    at async n (/app/web/.next/server/pages/api/auth/[...nextauth].js:1:3271)\n' +
    '    at async /app/node_modules/.pnpm/@sentry+nextjs@8.13.0_@opentelemetry+api@1.9.0_@opentelemetry+core@1.25.1_@opentelemetry+api@_ft7vzi4mthmzumntcxwwqwfz7a/node_modules/@sentry/nextjs/build/cjs/common/wrapApiHandlerWithSentry.js:90:43',
  name: 'PrismaClientKnownRequestError'
}
```

### To reproduce

use the following below given config to to deploy on kuberbets andthe it gives error->
```
`replicaCount: 1

image:
  repository: ghcr.io/langfuse/langfuse
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

langfuse:
  nodeEnv: production
  nextauth:
    url: host
    secret: changeme
  salt: changeme
  telemetryEnabled: True
  nextPublicSignUpDisabled: False
  enableExperimentalFeatures: False

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    external-dns.alpha.kubernetes.io/hostname: host
    external-dns.alpha.kubernetes.io/ttl: "60"
  hosts:
    - host: host
      paths:
        - path: /
          pathType: Prefix

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}

postgresql:
  deploy: false
  auth:
    username: XXXXX
    password: XXXXXXXXXXXXXXXXXX
    database: postgres_langfuse
  host: host:5432
  directUrl: postgresql://user:fpassword@host:5432
  shadowDatabaseUrl: postgresql://user:pass@host:5432`
```

### Are you interested to contribute a fix for this bug?

No
