### ISSUE TITLE
bug: Self Hosted CSP issue when using a custom domain name

### ISSUE THREAD

**Issue by AshDevFr** [langfuse/langfuse#3106]
### Describe the bug

I am deploying the application using `docker compose` and I have it setup behind a reverse proxy using traefik.

I have setup `NEXTAUTH_URL` to be my `https` address the is exposed by traefik.

When I launch the UI I get the following CSP errors:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://*.langfuse.com https://*.crisp.chat https://challenges.cloudflare.com https://*.sentry.io https://ph.langfuse.com https://static.cloudflareinsights.com https://*.stripe.com". Either the 'unsafe-inline' keyword, a hash ('sha256-eMuh8xiwcX72rRYNAGENurQBAcH7kLlAUQcoOri3BIo='), or a nonce ('nonce-...') is required to enable inline execution.
Understand this error

(7) Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src 'self' <URL>".
```

I believe it comes from [this block](https://github.com/langfuse/langfuse/blob/66c810e4a74afe7c308907d37cc77abc6f2d75ea/web/next.config.mjs#L13), is there a way to make it configurable or at least make it use `NEXTAUTH_URL` ?

### To reproduce

Deploy using the following docker compose / traefik config, launch the UI.

```
...
services:
  langfuse-db:
    image: postgres:16-alpine
    container_name: LangFuse-DB
    hostname: langfuse-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/langfuse-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: on-failure:5

  langfuse:
    image: langfuse/langfuse:latest
    container_name: LangFuse
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - langfuse-db
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@langfuse-db:5432/${POSTGRES_DB}?sslmode=disable
      NEXTAUTH_URL: https://langfuse.local.<my-domain>
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      SALT: ${SALT}
      LANGFUSE_CSP_ENFORCE_HTTPS: true
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: false
      TELEMETRY_ENABLED: false
      AUTH_DISABLE_SIGNUP: ${AUTH_DISABLE_SIGNUP}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langfuse.rule=Host(`langfuse.local.<my-domain>`)"
      - "traefik.http.routers.langfuse.entrypoints=https"
      - "traefik.http.routers.langfuse.tls=true"
      - "traefik.http.routers.langfuse.tls.certresolver=cloudflare"
      - "traefik.http.routers.langfuse.middlewares=default-headers@file"
      - "traefik.http.services.langfuse.loadbalancer.server.port=3000"
```

### Are you interested to contribute a fix for this bug?

Yes
