### ISSUE TITLE
bug: Headless Initialization - Invalid email

### ISSUE THREAD

**Issue by pwnywiz** [langfuse/langfuse#3398]
### Describe the bug

I am trying to run a local deployment of Langfuse with docker compose and headless initialization, however i keep getting the following error `Invalid environment variables: { LANGFUSE_INIT_USER_EMAIL: [ 'Invalid email' ] }`.
You can find below the error trace, as well as the instructions of my docker compose yaml file.
Is there anything that im missing?

 ✓ Starting...
❌ Invalid environment variables: { LANGFUSE_INIT_USER_EMAIL: [ 'Invalid email' ] }
 ✓ Ready in 759ms
Failed to prepare server Error: An error occurred while loading instrumentation hook: Invalid environment variables
    at t (/app/web/.next/server/chunks/9040.js:1:5058)
    at I (/app/web/.next/server/chunks/9040.js:1:5238)
    at /app/web/.next/server/chunks/9040.js:1:5546
    at 892212 (/app/web/.next/server/chunks/9040.js:1:5623)
    at t (/app/web/.next/server/webpack-runtime.js:1:479)
    at /app/web/.next/server/chunks/9040.js:1:2699
    at t.a (/app/web/.next/server/webpack-runtime.js:1:1260)
    at 799040 (/app/web/.next/server/chunks/9040.js:1:2665)
    at Function.t (/app/web/.next/server/webpack-runtime.js:1:479)
    at async Module.s (/app/web/.next/server/instrumentation.js:1:2242)
❌ Invalid environment variables: { LANGFUSE_INIT_USER_EMAIL: [ 'Invalid email' ] }

### To reproduce

```
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_INIT_ORG_ID="seed-org-id"
      - LANGFUSE_INIT_ORG_NAME="Seed Org"
      - LANGFUSE_INIT_PROJECT_ID="7a88fb47-b4e2-43b8-a06c-a5ce950dc53a"
      - LANGFUSE_INIT_PROJECT_NAME="Seed Project"
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY="pk-lf-1234567890"
      - LANGFUSE_INIT_PROJECT_SECRET_KEY="sk-lf-1234567890"
      - LANGFUSE_INIT_USER_EMAIL="demo@langfuse.com"
      - LANGFUSE_INIT_USER_NAME="Demo User"
      - LANGFUSE_INIT_USER_PASSWORD="password"
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

### SDK and container versions

Langfuse: 2.49.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment]
I was able to reproduce this with the provided docker compose file.<br><br>If you do not double-quote the values it works as expected. Working example below:

```
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}
      - LANGFUSE_INIT_ORG_ID=seed-org-id
      - LANGFUSE_INIT_ORG_NAME=Seed Org
      - LANGFUSE_INIT_PROJECT_ID=7a88fb47-b4e2-43b8-a06c-a5ce950dc53a
      - LANGFUSE_INIT_PROJECT_NAME=Seed Project
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=pk-lf-1234567890
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=sk-lf-1234567890
      - LANGFUSE_INIT_USER_EMAIL=demo@langfuse.com
      - LANGFUSE_INIT_USER_NAME=Demo User
      - LANGFUSE_INIT_USER_PASSWORD=password
  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```
