### ISSUE TITLE
bug: `DATABASE_URL` is now required and startup fails, even when all of DATABASE_HOST, DATABASE_USERNAME, DATABASE_PASSWORD and DATABASE_NAME are provided

### ISSUE THREAD

**Issue by xdumaine** [langfuse/langfuse#3433]
### Describe the bug

Previously (we were on 2.61.1) DATABASE_URL was optional if DATABASE_HOST, DATABASE_USERNAME, DATABASE_PASSWORD and DATABASE_NAME were all provided, because entrypoint would construct the URL from those env variables. Now (trying to upgrade to 2.80.0) we get `Error: Required database environment variables are not set. Provide a postgres url for DATABASE_URL.` on startup

### To reproduce

Run self-hosted with DATABASE_HOST, DATABASE_USERNAME, DATABASE_PASSWORD and DATABASE_NAME set and DATABASE_URL unset

### SDK and container versions

2.80.0 is failing, 2.61.1 worked. Not sure which specific version broke it.

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment]
Thanks for sharing, looking into this rn

**Comment by xdumaine** [comment]
It's possible that the error is misleading - relevant code appears to be [here](https://github.com/langfuse/langfuse/blob/c483293b10b577cac1ff675e1dcff1b06b577f1e/worker/entrypoint.sh#L5-L15) and [here](https://github.com/langfuse/langfuse/blob/c483293b10b577cac1ff675e1dcff1b06b577f1e/web/entrypoint.sh#L5-L15) I'm looking a little closer.

**Comment by marcklingen** [comment]
This Yes, this seems to be a configuration issue, I was unable to reproduce this with this docker compose file

```yml
services:
  langfuse-server:
    image: langfuse/langfuse:2
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000 # generate via `openssl rand -hex 32`
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```
