### ISSUE TITLE
bug: Cannot find module '/app/server.js'

### ISSUE THREAD

**Issue by ziiw** [langfuse/langfuse#3820]
### Describe the bug

While preparing a self-host Docker, the langfuse container is not starting properly. the migrations are done, the database contains all the tables. But it can't pass this error while booting

```sh
langfuse-1  | Script executed successfully.
langfuse-1  | Prisma schema loaded from packages/shared/prisma/schema.prisma
langfuse-1  | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
langfuse-1  |
langfuse-1  | 256 migrations found in prisma/migrations
langfuse-1  |
langfuse-1  |
langfuse-1  | No pending migrations to apply.
langfuse-1  | node:internal/modules/cjs/loader:1228
langfuse-1  |   throw err;
langfuse-1  |   ^
langfuse-1  |
langfuse-1  | Error: Cannot find module '/app/server.js'
langfuse-1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
langfuse-1  |     at Module._load (node:internal/modules/cjs/loader:1051:27)
langfuse-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
langfuse-1  |     at node:internal/main/run_main_module:28:49 {
langfuse-1  |   code: 'MODULE_NOT_FOUND',
langfuse-1  |   requireStack: []
langfuse-1  | }
langfuse-1  |
langfuse-1  | Node.js v20.18.0
langfuse-1 exited with code 1
```

### To reproduce

`docker-compose.yml`
```yml
version: '3.8'

services:
  langfuse:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```

`Dockerfile`
```yml
# Use the official Langfuse image
FROM langfuse/langfuse:2

# Set environment variables
ENV DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
ENV NEXTAUTH_URL=http://localhost:3001
ENV NEXTAUTH_SECRET=mysecret
ENV SALT=mysalt
ENV ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000

# Headless Initialization variables
ENV LANGFUSE_INIT_ORG_ID=my-org
ENV LANGFUSE_INIT_ORG_NAME=MyOrg
ENV LANGFUSE_INIT_PROJECT_ID=project-id
ENV LANGFUSE_INIT_PROJECT_NAME=Project
ENV LANGFUSE_INIT_PROJECT_PUBLIC_KEY=lf_pk_1234567890
ENV LANGFUSE_INIT_PROJECT_SECRET_KEY=lf_sk_1234567890
ENV LANGFUSE_INIT_USER_EMAIL=user@example.com
ENV LANGFUSE_INIT_USER_NAME=JohnDoe
ENV LANGFUSE_INIT_USER_PASSWORD=password1234

# Expose port 3001
EXPOSE 3001

# Set the command to run the Langfuse server
CMD ["node", "server.js"]
```

`docker-compose up --build`

### SDK and container versions

langfuse v2
nodeJS v20.18
Postgres v14

### Are you interested to contribute a fix for this bug?

Yes
