### ISSUE TITLE
bug: LANGFUSE_INIT_* environment variables are not respected

### ISSUE THREAD

**Issue by eabruzzese** [langfuse/langfuse#4244]
### Describe the bug

When setting up Langfuse in a Docker Compose configuration, setting the `LANGFUSE_INIT_*` environment variables appears to have no effect: no organizations, projects, or users are created in the database.

### To reproduce

Using the following `docker-compose.yaml`, issue a `docker compose up` command, then attempt to log in as `dev@example.com` with the password `password`. It'll fail.

```yaml
volumes:
  langfuse-postgres:

services:
  langfuse:
    restart: unless-stopped
    image: langfuse/langfuse:2
    depends_on:
      langfuse-postgres:
        condition: service_healthy
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@langfuse-postgres:5432/postgres
      - NEXTAUTH_SECRET=insecure-secret
      - SALT=insecure-salt
      - ENCRYPTION_KEY=d4f11628305d24f8c5b9e78f99f8bb9ac35615f462b90b08091d74c34687cd23
      - NEXTAUTH_URL=http://localhost:3000
      - TELEMETRY_ENABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
      - LANGFUSE_INIT_ORG_ID=test-organization
      - LANGFUSE_INIT_ORG_NAME=Test Organization
      - LANGFUSE_INIT_PROJECT_ID=test-project
      - LANGFUSE_INIT_PROJECT_NAME=Test Project
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=lf_pk_1234567890
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=lf_sk_1234567890
      - LANGFUSE_INIT_USER_EMAIL=dev@example.com
      - LANGFUSE_INIT_USER_NAME=Local Developer
      - LANGFUSE_INIT_USER_PASSWORD=development-only

  langfuse-postgres:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - langfuse-postgres:/var/lib/postgresql/data
```

If you connect to the database and query for orgs, projects, or users, you'll see that none were created.

### Are you interested to contribute a fix for this bug?

Yes
