### ISSUE TITLE
bug:  Langfuse failing to start Azure Web App

### ISSUE THREAD

**Issue by hasibfox** [langfuse/langfuse#4623]
### Describe the bug

Running the docker config file below. It applies all the seemingly right configurations and migrations, but upon opening my Azure Web App link, with the following information. 

... Running init scripts...
... Ready in 22.3s

... Stopping site myapp because it failed during startup.

### To reproduce

```
services: 
  backend:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: langfuse/langfuse:sha-9375250  
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@backend:5432/postgres
      - NEXTAUTH_URL=http://localhost:80
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000

    depends_on:
      backend:
        condition: service_healthy
```

### SDK and container versions

Multi-container Azure Web App via Docker Compose Config
Docker Postgres Image
Docker Self-Hosted Image

### Are you interested to contribute a fix for this bug?

No
