### ISSUE TITLE
bug: MediaContentType in OpenAPI spec should be an enum

### ISSUE THREAD

**Issue by STRRL** [langfuse/langfuse#4626]
### Describe the bug

I am trying to integrate langfuse with golang, and thanks team I found a openapi spec.

https://cloud.langfuse.com/generated/api/openapi.yml

But when I generate golang codes with latest API and github.com/oapi-codegen/oapi-codegen, it could not works well. There did exists a syntax error in generated code:

and I think this issue caused by:

- https://github.com/langfuse/langfuse/blob/6be87994a98e0338e4115a6f61cf3f7beace4110/web/public/generated/api/openapi.yml#L4057-L4063
- https://github.com/langfuse/langfuse/blob/6be87994a98e0338e4115a6f61cf3f7beace4110/fern/apis/server/definition/media.yml#L101-L103

using `enum` instead of `literal` would fix it

### To reproduce

with config file `codegen_config.yaml`

```yaml
# codegen_config.yaml
package: openapi
output: langfuse.zz_generated.go
generate:
  echo-server: false
  client: true
  models: true
  embedded-spec: true
```

execute `go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=codegen_config.yaml https://cloud.langfuse.com/generated/api/openapi.yml` will generate a bad go file:

![image](https://github.com/user-attachments/assets/d5186b3b-bfa3-4642-827e-dafffbc1691e)

### Are you interested to contribute a fix for this bug?

Yes
