### ISSUE TITLE
bug: errors prevent self-hosted langfuse from rendering dashboard/traces fields: "Function dateDiff does not support 'milliseconds' unit" - "internal error traces.metrics"

### ISSUE THREAD

**Issue by misterfancysocks** [langfuse/langfuse#4880]
### Describe the bug

On self-hosted Langfuse(latest version using adapted [docker-compose.yml](https://github.com/langfuse/langfuse/blob/main/docker-compose.yml)) I receive the following errors when trying to view traces. These errors prevent me from viewing elements of the dashboard and also prevent several summary fields (pictures below) from traces from loading.

Front End:

> ![CleanShot 2025-01-02 at 17 48 31@2x](https://github.com/user-attachments/assets/9f1bec65-ee84-4f07-8026-63017cbc7ceb)

Back End:

> ![CleanShot 2025-01-02 at 17 57 38@2x](https://github.com/user-attachments/assets/f4674d25-9738-4713-b555-45bb4a7e2ba5)

### To reproduce

Docker compose on local host
Existing postgres db with 'langfuse' schema
AWS S3 storage
headless setup

```yaml
services:
  db:
    image: postgres:16
    container_name: consumio-db
    environment:
      POSTGRES_DB: consumio
      POSTGRES_USER: preston
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - consumio-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U preston -d consumio"]
      interval: 10s
      timeout: 5s
      retries: 5
    stop_signal: SIGTERM
    stop_grace_period: 61s

  langfuse:
    image: langfuse/langfuse:3
    container_name: consumio-langfuse
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://preston@db:5432/consumio?schema=langfuse
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
      - CLICKHOUSE_MIGRATION_CLUSTER_DISABLED="true"
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=redis
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=
      - LANGFUSE_INIT_ORG_ID=
      - LANGFUSE_INIT_ORG_NAME=
      - LANGFUSE_INIT_PROJECT_ID=
      - LANGFUSE_INIT_PROJECT_NAME=
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=
      - LANGFUSE_INIT_USER_EMAIL=
      - LANGFUSE_INIT_USER_NAME=
      - LANGFUSE_INIT_USER_PASSWORD=
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      db:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: consumio-redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    container_name: consumio-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - CLICKHOUSE_MIGRATION_CLUSTER_DISABLED="true"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  langfuse-worker:
    image: langfuse/langfuse-worker:3
    container_name: consumio-langfuse-worker
    ports:
      - "3030:3030"
    environment:
      - DATABASE_URL=postgresql://preston@db:5432/consumio?schema=langfuse
      - SALT=mysalt
      - ENCRYPTION_KEY=
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
      - CLICKHOUSE_MIGRATION_CLUSTER_DISABLED="true"
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=redis
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=
      - LANGFUSE_INIT_ORG_ID=
      - LANGFUSE_INIT_ORG_NAME=
      - LANGFUSE_INIT_PROJECT_ID=
      - LANGFUSE_INIT_PROJECT_NAME=
      - LANGFUSE_INIT_PROJECT_PUBLIC_KEY=
      - LANGFUSE_INIT_PROJECT_SECRET_KEY=
      - LANGFUSE_INIT_USER_EMAIL=
      - LANGFUSE_INIT_USER_NAME=
      - LANGFUSE_INIT_USER_PASSWORD=
    depends_on:
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  consumio-postgres-data:
```

### SDK and container versions

latest version; fresh install

### Are you interested to contribute a fix for this bug?

No
