### ISSUE TITLE
bug: Langflow received 404 error from langfuse when sending traces

### ISSUE THREAD

**Issue by matthieudelaro** [langfuse/langfuse#518]
### Describe the bug

Running a flow from the UI in LangFlow:
<img width="653" alt="grafik" src="https://github.com/langfuse/langfuse/assets/2452725/5e72844f-2d9b-4f7a-97c5-bd021fb6054c">

Error log from langfuse handler:
```
langfuse-friday-langflow-1         | error uploading: [Langfuse] <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/_next/static/css/6a18914c8c2b9bdb.css" as="style" crossorigin=""/><link rel="stylesheet" href="/_next/static/css/6a18914c8c2b9bdb.css" crossorigin="" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" crossorigin="" nomodule="" src="/_next/static/chunks/polyfills-c67a75d1b6f99dc8.js"></script><script src="/_next/static/chunks/webpack-3c4438a4b0b94bc6.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/framework-467b11a89995b152.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/main-2e4feaa5073d1dc0.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_app-19e7fe597530109b.js" defer="" crossorigin=""></script><script src="/_next/static/chunks/pages/_error-a59e2db023c5e431.js" defer="" crossorigin=""></script><script src="/_next/static/4O8NzcJ97u9By3d3-PhMf/_buildManifest.js" defer="" crossorigin=""></script><script src="/_next/static/4O8NzcJ97u9By3d3-PhMf/_ssgManifest.js" defer="" crossorigin=""></script></head><body><div id="__next"><div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8"><div class="sm:mx-auto sm:w-full sm:max-w-md"><img src="/icon256.png" width="42" height="42" alt="Langfuse Icon" class="mx-auto motion-safe:animate-spin"/><h2 class="mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-gray-900">Loading<!-- --> ...</h2></div></div></div><script id="__NEXT_DATA__" type="application/json" crossorigin="">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"4O8NzcJ97u9By3d3-PhMf","nextExport":true,"isFallback":false,"gip":true,"locale":"en","locales":["en"],"defaultLocale":"en","scriptLoader":[]}</script></body></html> (404)
```

I encounter the issue with both a local langfuse (docker-compose).
On langfuse cloud, there isn't any error log. But traces either:
1) do not appear in the dashboard, or 
2) appear with a delay of several minutes, giving the impression that it doesn't work. Latest two attempt: ~5 min of delay worked for 1/2 traces.

### To reproduce

# Files to reproduce locally
## Dockerfile
```
FROM python:3.10-slim

RUN apt-get update && apt-get install gcc g++ git make -y && apt-get clean \
	&& rm -rf /var/lib/apt/lists/*
RUN useradd -m -u 1000 user
USER user
ENV HOME=/home/user \
	PATH=/home/user/.local/bin:$PATH

WORKDIR $HOME/app

COPY --chown=user . $HOME/app

# RUN pip install langflow>==0.5.0 numexpr langchain langfuse -U --user
RUN pip install langflow>==0.5.0 numexpr -U --user
CMD ["python", "-m", "langflow", "run", "--host", "0.0.0.0", "--port", "7860"]
```

## docker-compose.yml
```
version: "3.5"

services:  
  langflow:
    depends_on:
      - langfuse-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    env_file:
    - ./.env
    command: langflow run --host 0.0.0.0
    volumes:
      - ./flows:/flows

  langfuse-server:
    image: ghcr.io/langfuse/langfuse:latest
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - NEXTAUTH_URL=http:localhost:3000
      - TELEMETRY_ENABLED=${TELEMETRY_ENABLED:-true}
      - NEXT_PUBLIC_SIGN_UP_DISABLED=${NEXT_PUBLIC_SIGN_UP_DISABLED:-false}
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=${LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES:-false}

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
```

# .env
```
OPENAI_API_KEY=sk-...

LANGFLOW_LANGFUSE_SECRET_KEY=sk-lf- # to be generated in the web interface of langfuse
LANGFLOW_LANGFUSE_PUBLIC_KEY=pk-lf- # to be generated in the web interface of langfuse
LANGFLOW_LANGFUSE_HOST=https://cloud.langfuse.com # must be set for some of your services to work
LANGFLOW_LANGFUSE_HOST=http://langfuse-server:3000 # local address of the langfuse server

```

# Steps
```
docker compose up --build
# check python modules versions:
docker compose exec langflow bash -c "pip list" | grep lang
# In my case, it's :
# langchain                                    0.0.320
# langchain-experimental                       0.0.8
# langdetect                                   1.0.9
# langflow                                     0.5.7
# langfuse                                     1.4.1
# langsmith                                    0.0.64
# create account and API keys in langfuse. Copu-paste them in langflow
docker compose restart langflow
# visit langflow web UI. Create new project
# import [PoC_Calculator_Wikipedia.json](https://github.com/langfuse/langfuse/files/13389278/PoC_Calculator_Wikipedia.json)
# open chat window, ask "How much are 42 + 42 ?"
Look at the logs of langflow, you should see the same as above.
```

The issue is similar with langfuse cloud, except there there isn't any logs on the client size (langflow handler).
Here is how to check-up the setup:
```
docker compose exec langflow bash -c "env" | grep LANGFUSE
# LANGFLOW_LANGFUSE_PUBLIC_KEY=pk-lf-a9c20baa-7869-4319-...
# LANGFLOW_LANGFUSE_HOST=https://cloud.langfuse.com
# LANGFLOW_LANGFUSE_SECRET_KEY=sk-lf-...
```
