### ISSUE TITLE
bug: enable_preview_features: true sends unnecessary metadata to model

### ISSUE THREAD

**Issue by yigitkonur** [langfuse/langfuse#5339]
### Describe the bug

I noticed this error like this: OpenAI was giving me an error about sending too much metadata. The error was: 

`BadRequestError: OpenAIException - Error code: 400 - {'error': {'message': "Invalid 'metadata': too many properties. Expected an object with at most 16 properties, but got an object with 29 properties instead.", 'type': 'invalid_request_error', 'param': 'metadata', 'code': 'object_above_max_properties'}}`

I turned off the parameters one by one and realized that when `enable_preview_features` is set to `true`, it sends too much metadata.

Here's the request I sent:

```bash
curl --request POST \
  --url http://127.0.0.1:1453/v1/chat/completions \
  --header 'authorization: Bearer sk-xxx' \
  --header 'content-type: application/json' \
  --data '{
  "messages": [
    {
      "role": "user",
      "content": "1+1?"
    }
  ],
  "model": "gpt-4o"
}'
```

Here is the request passed to OpenAI server:

```json
{
  "messages": [
    {
      "role": "user",
      "content": "1+1?"
    }
  ],
  "model": "gpt-4o",
  "metadata": {
    "requester_metadata": {},
    "user_api_key_hash": "xxx",
    "user_api_key_alias": null,
    "user_api_key_team_id": null,
    "user_api_key_user_id": "default_user_id",
    "user_api_key_org_id": null,
    "user_api_key_team_alias": null,
    "user_api_key_end_user_id": null,
    "user_api_key": "xxx",
    "user_api_end_user_max_budget": null,
    "litellm_api_version": "1.59.9",
    "global_max_parallel_requests": null,
    "user_api_key_team_max_budget": null,
    "user_api_key_team_spend": null,
    "user_api_key_spend": 0,
    "user_api_key_max_budget": null,
    "user_api_key_model_max_budget": {},
    "user_api_key_metadata": {},
    "headers": {
      "accept": "application/json, text/plain, */*",
      "content-type": "application/json",
      "user-agent": "bruno-runtime/1.38.1",
      "request-start-time": "1738549443505",
      "content-length": "102",
      "accept-encoding": "gzip, compress, deflate, br",
      "host": "127.0.0.1:1453",
      "connection": "keep-alive"
    },
    "endpoint": "http://127.0.0.1:1453/v1/chat/completions",
    "litellm_parent_otel_span": null,
    "requester_ip_address": "",
    "model_group": "gpt-4o",
    "model_group_size": 1,
    "deployment": "openai/gpt-4o",
    "model_info": {
      "id": "xxx",
      "db_model": false
    },
    "api_base": "https://webhook.site/xxx",
    "caching_groups": null
  }
}
```

I've enabled this to enable stream = true option for o1 models but seems like creating extra issues.

### To reproduce

Try with such config to get JSON body by websites like webhook dot site.

# Issue

```yaml
# LiteLLM Global Settings
litellm_settings:
  cache: false
  drop_params: true
  enable_preview_features: true
  json_logs: false
  redact_messages_in_exceptions: false
  redact_user_api_key_info: false
  turn_off_message_logging: true
  force_ipv4: true
  
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: sk-proj-xxx
      api_base: https://webhook.site/xxx
```

# No Issue

```
# LiteLLM Global Settings
litellm_settings:
  cache: false
  drop_params: true
  enable_preview_features: false
  json_logs: false
  redact_messages_in_exceptions: false
  redact_user_api_key_info: false
  turn_off_message_logging: true
  force_ipv4: true
  
model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: sk-proj-xxx
      api_base: https://webhook.site/xxx
```

### SDK and container versions

Latest version

### Are you interested to contribute a fix for this bug?

No
