### ISSUE TITLE
bug: Provider name for Azure ambiguous

### ISSUE THREAD

**Issue by rodrigobdz** [langfuse/langfuse#5487]
### Describe the bug

[TL;DR:](https://github.com/langfuse/langfuse/issues/5487#issuecomment-2653046015) The issue is that the provider name could be `AZURE` or `AZURE_AD` depending on the variable. This should be consistent.
---

Initial error:

Sign up with SSO leads to error:

> Please sign in with the same provider that you used to create this account.
> Contact support if this error is unexpected.

### To reproduce

1. Install Langfuse on Kubernetes cluster using [Helm chart](https://github.com/langfuse/langfuse-k8s)
2. Add required Azure AD variables for SSO support—see Helm chart below
    <details><summary>Helm chart</summary>
    <p>

    ```yaml
    replicaCount: 1

    image:
      repository: langfuse/langfuse
      pullPolicy: Always
      tag: 3

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    langfuse:
      port: 3000
      nodeEnv: production
      next:
        healthcheckBasePath: ""
      nextauth:
        url: https://mydomain.com
        secret: changeme
      salt: changeme
      licenseKey: ""
      telemetryEnabled: False
      nextPublicSignUpDisabled: False
      enableExperimentalFeatures: False
      extraContainers: []
      extraVolumes: []
      extraInitContainers: []
      extraVolumeMounts: []

      web:
        resources: {}
        hpa:
          enabled: false
          minReplicas: 1
          maxReplicas: 2
          targetCPUUtilizationPercentage: 50
        vpa:
          enabled: false
          controlledResources: []
          maxAllowed: {}
          minAllowed: {}
          updatePolicy:
            updateMode: Auto
      worker:
        resources: {}
        hpa:
          enabled: false
          minReplicas: 1
          maxReplicas: 2
          targetCPUUtilizationPercentage: 50
        vpa:
          enabled: false
          controlledResources: []
          maxAllowed: {}
          minAllowed: {}
          updatePolicy:
            updateMode: Auto

      additionalEnv:
        # SSO
        - name: "AUTH_AZURE_AD_CLIENT_ID"
          value: ""********"
        - name: "AUTH_AZURE_AD_CLIENT_SECRET"
          value: "********"
        - name: "AUTH_AZURE_AD_TENANT_ID"
          value: "********"
        # REDIS
        - name: "REDIS_CONNECTION_STRING"
          value: "redis://default:changeme@langfuse-valkey-primary:6379/0"
        # CLICKHOUSE
        - name: "CLICKHOUSE_MIGRATION_URL"
          value: "clickhouse://langfuse-clickhouse:9000"
        - name: "CLICKHOUSE_URL"
          value: "http://langfuse-clickhouse:8123"
        - name: "CLICKHOUSE_USER"
          value: "default"
        - name: "CLICKHOUSE_PASSWORD"
          value: "changeme"
        # S3 / MinIO
        - name: "LANGFUSE_S3_EVENT_UPLOAD_ENABLED"
          value: "true"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_BUCKET"
          value: "langfuse"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_REGION"
          value: "auto"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID"
          value: "minio"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY"
          value: "miniosecret"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT"
          value: "http://langfuse-minio:9000"
        - name: "LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE"
          value: "true"

    serviceAccount:
      create: true
      annotations: {}
      name: ""

    podAnnotations: {}

    podSecurityContext: {}

    securityContext: {}

    service:
      type: ClusterIP
      port: 3000
      nodePort: ""

    ingress:
      enabled: true
      hosts:
        - host: mydomain.com
          paths:
            - path: /
              pathType: Prefix

    resources: {}

    nodeSelector: {}

    tolerations: []

    affinity: {}

    postgresql:
      host: langfuse-postgresql
      auth:
        username: postgres
        password: postgres
        database: postgres_langfuse
      deploy: true
      architecture: standalone
      primary:
        service:
          ports:
            postgresql: 5432

    clickhouse:
      deploy: true
      shards: 1 # Fixed. Langfuse does not support multi-shard clusters.
      replicaCount: 3
      resourcesPreset: 2xlarge
      auth:
        username: default
        password: changeme

    valkey:
      deploy: true
      architecture: standalone
      primary:
        extraFlags:
          - "--maxmemory-policy noeviction"
      auth:
        password: changeme

    minio:
      deploy: true
      defaultBuckets: 'langfuse'
      auth:
        rootUser: 'minio'
        rootPassword: 'miniosecret'

    extraManifests: []
    ```

    </p>
    </details> 
4. Add user `john@doe.com` to Azure AD group linked to Langfuse
5. As user `john@doe.com`, navigate to `https://mydomain.com/auth/sign-up`
6. Click on `sign up with Azure AD`
    <details><summary>Screenshot</summary>
    <p>
    <img width="537" alt="Image" src="https://github.com/user-attachments/assets/df446314-4354-42ad-9dbf-32553bfa496c" />
    </p>
    </details> 

### Are you interested to contribute a fix for this bug?

No
