### ISSUE TITLE
bug: Background migration failed, migrateEventLogToBlobStorageRefTable module not found

### ISSUE THREAD

**Issue by pi-infected** [langfuse/langfuse#7315]
### Describe the bug

Hi, 

I have the last version of langfuse and I have this bug on the worker :

"Error running background migrations Cannot find module './migrateEventLogToBlobStorageRefTable'"

It was working well for a while, then I reorganized my docker-compose and suddenly langfuse was not able to use the observations and trace tables from clickhouse. I managed the problem (It was extremely painful so I spare you the details).  But the last migration won't execute because of this bug. 

It seems weird because I have the v3.68 of langfuse so this module should be present. 

Btw even after the observations and traces table succeded, the langfuse worker cannot find the observations and traces table in clickhouse, so there is constant errors in my logs.  I've checked and the tables are there. 

Examples :

```
2025-06-15T20:31:01.423Z error  Queue Job ingestion-job with id 378 in ingestion-queue failed Unknown table expression identifier 'observations' in scope SELECT * FROM observations WHERE (project_id = 'cmby2z9bw0006nv077p8ytfr8') AND (id = 'time-20-30-34-124865_chatcmpl-BioHq4R8hCzGo8mWNSb9PhabTxht4') AND (type = 'GENERATION') AND (start_time >= _CAST('1750019434.124', 'DateTime64(3)')) ORDER BY event_ts DESC LIMIT 1 BY id, project_id SETTINGS use_query_cache = false. 
Error: Unknown table expression identifier 'observations' in scope SELECT * FROM observations WHERE (project_id = 'cmby2z9bw0006nv077p8ytfr8') AND (id = 'time-20-30-34-124865_chatcmpl-BioHq4R8hCzGo8mWNSb9PhabTxht4') AND (type = 'GENERATION') AND (start_time >= _CAST('1750019434.124', 'DateTime64(3)')) ORDER BY event_ts DESC LIMIT 1 BY id, project_id SETTINGS use_query_cache = false. 
    at parseError (/app/node_modules/.pnpm/@clickhouse+client-common@1.4.0/node_modules/@clickhouse/client-common/dist/error/parse_error.js:34:16)
    at ClientRequest.onResponse (/app/node_modules/.pnpm/@clickhouse+client@1.4.0/node_modules/@clickhouse/client/dist/connection/node_base_connection.js:365:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here is my configuration : 

```
langfuse:
    container_name: langfuse
    image: "langfuse/langfuse:latest"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/langfuse?sslmode=disable
      - NEXTAUTH_SECRET=${LANGFUSE_SECRET}
      - NEXTAUTH_URL=http://langfuse.localhost
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
      - SALT=${LANGFUSE_SALT}
      - LANGFUSE_CSP_ENFORCE_HTTPS=false
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
      - CLICKHOUSE_USER=${CLICKHOUSE_ADMIN_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_ADMIN_PASSWORD}
      - CLICKHOUSE_DB=langfuse
      - CLICKHOUSE_MIGRATION_SSL=false
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - LANGFUSE_AUTO_CLICKHOUSE_MIGRATION_DISABLED=false
      - REDIS_CONNECTION_STRING=redis://default:${REDIS_PASSWORD}@redis:6379/0
      - LANGFUSE_S3_EVENT_UPLOAD_ENABLED=true
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=us-east-1
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${MINIO_COMMON_ACCESS_KEY}
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_COMMON_SECRET_KEY}
      - LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000
      - LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
      - LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
      - LOG_LEVEL=ERROR
      - NODE_ENV_LOG_LEVEL=error
      - LANGFUSE_READ_FROM_POSTGRES_ONLY=true
      - LANGFUSE_ENABLE_BACKGROUND_MIGRATIONS=true
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langfuse.rule=Host(`langfuse.localhost`)"
      - "traefik.http.routers.langfuse.entrypoints=web"
      - "traefik.http.services.langfuse.loadbalancer.server.port=3000"
      - "traefik.http.routers.langfuse.middlewares=crowdsec@file"

  langfuse-worker:
    container_name: langfuse-worker
    image: "langfuse/langfuse-worker:latest"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/langfuse?sslmode=disable
      - NEXTAUTH_SECRET=${LANGFUSE_SECRET}
      - NEXTAUTH_URL=http://langfuse.localhost
      - ENCRYPTION_KEY=${LANGFUSE_ENCRYPTION_KEY}
      - SALT=${LANGFUSE_SALT}
      - LANGFUSE_CSP_ENFORCE_HTTPS=false
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - CLICKHOUSE_URL=http://clickhouse:8123
      - CLICKHOUSE_MIGRATION_URL=clickhouse://clickhouse:9000
      - CLICKHOUSE_USER=${CLICKHOUSE_ADMIN_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_ADMIN_PASSWORD}
      - CLICKHOUSE_DB=langfuse
      - CLICKHOUSE_MIGRATION_SSL=false
      - CLICKHOUSE_CLUSTER_ENABLED=false
      - REDIS_CONNECTION_STRING=redis://default:${REDIS_PASSWORD}@redis:6379/0
      - LANGFUSE_S3_EVENT_UPLOAD_ENABLED=true
      - LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
      - LANGFUSE_S3_EVENT_UPLOAD_REGION=us-east-1
      - LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=${MINIO_COMMON_ACCESS_KEY}
      - LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_COMMON_SECRET_KEY}
      - LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://minio:9000
      - LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
      - LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
      - LOG_LEVEL=ERROR
      - NODE_ENV_LOG_LEVEL=error
      - LANGFUSE_READ_FROM_POSTGRES_ONLY=true
      - LANGFUSE_ENABLE_BACKGROUND_MIGRATIONS=true
    networks:
      - traefik
    dns:
      - 172.20.0.10
      - 8.8.8.8
    labels:
      - "traefik.enable=false"
```

I cannot give you a minimal working example for reproduction. 

### To reproduce

I cannot give you a minimal working example sorry. 

### Are you interested to contribute a fix for this bug?

No
