### ISSUE TITLE
bug: CallbackHandler

### ISSUE THREAD

**Issue by grimo8805** [langfuse/langfuse#7495]
### Describe the bug

trying to use the langfuse's CallbackHandler(), with the create_react_agent() service which is used for langgraph agents.

getting the following error, 

Failed to export batch code: 404, reason: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/langfuse/_next/static/css/0a37468f281f4fde.css" as="style"/><link rel="stylesheet" href="/langfuse/_next/static/css/0a37468f281f4fde.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/langfuse/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script src="/langfuse/_next/static/chunks/webpack-5490f9c04512822f.js" defer=""></script><script src="/langfuse/_next/static/chunks/framework-d2dcb18632b956b2.js" defer=""></script><script src="/langfuse/_next/static/chunks/main-1b61adfb972c2a5d.js" defer=""></script><script src="/langfuse/_next/static/chunks/pages/_app-945871dd503b5be0.js" defer=""></script><script src="/langfuse/_next/static/chunks/pages/_error-a6b891bf0b43bbee.js" defer=""></script><script src="/langfuse/_next/static/ue3gGE60Ac4nvOrYmqPNY/_buildManifest.js" defer=""></script><script src="/langfuse/_next/static/ue3gGE60Ac4nvOrYmqPNY/_ssgManifest.js" defer=""></script></head><body><div id="__next"><script>!function(){try{var d=document.documentElement,c=d.classList;c.remove('light','dark');var e=localStorage.getItem('theme');if('system'===e||(!e&&true)){var t='(prefers-color-scheme: dark)',m=window.matchMedia(t);if(m.media!==t||m.matches){d.style.colorScheme = 'dark';c.add('dark')}else{d.style.colorScheme = 'light';c.add('light')}}else if(e){c.add(e|| '')}if(e==='light'||e==='dark')d.style.colorScheme=e}catch(e){}}()</script><div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8" data-sentry-component="Spinner" data-sentry-source-file="spinner.tsx"><div class="sm:mx-auto sm:w-full sm:max-w-md"><img src="/langfuse/icon.svg" width="42" height="42" alt="Langfuse Icon" class="mx-auto motion-safe:animate-spin" data-sentry-component="LangfuseIcon" data-sentry-source-file="LangfuseLogo.tsx"/><h2 class="mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-primary">Loading ...</h2></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"ue3gGE60Ac4nvOrYmqPNY","assetPrefix":"/langfuse","nextExport":true,"isFallback":false,"gip":true,"locale":"en","locales":["en"],"defaultLocale":"en","scriptLoader":[]}</script></body></html>

### To reproduce

**server.py**
```
from mcp.server.fastmcp import FastMCP
mcp = FastMCP("StringTools")
@mcp.tool()
def reverse_string(text: str) -> str:
    """Reverses the given string."""
    return text[::-1]
@mcp.tool()
def count_words(text: str) -> int:
    """Counts the number of words in a sentence."""
    return len(text.split())
if __name__ == "__main__":
    mcp.run(transport="stdio")
```

client.py

```
import asyncio
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client
from langchain_mcp_adapters.tools import load_mcp_tools
from langgraph.prebuilt import create_react_agent
from langchain_openai import ChatOpenAI
import os
from langchain_mcp_adapters.tools import load_mcp_tools
from  langgraph.prebuilt import create_react_agent
from langfuse.langchain import CallbackHandler

 
# Initialize Langfuse CallbackHandler for Langchain (tracing)
langfuse_handler = CallbackHandler()

model = ChatOpenAI(model="gpt-4o",temperature=0.1)# Use a model available via Ollama
#Using WatsonX
parameters = {
    "decoding_method": "sample",
    "max_new_tokens": 4000,
    "min_new_tokens": 1,
    "temperature": 1,
    "top_k": 50,
    "top_p": 1,
}


async def main():
    server_params = StdioServerParameters(
        command="python",
        args=["server.py"],  
    )
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            tools = await load_mcp_tools(session)
                        
            agent = create_react_agent(model, tools,)
            
     
            msg1 = {"messages": "Reverse the string 'hello world'"}
            # msg2 = {"messages": "How many words are in the sentence 'Model Context Protocol is powerful'?"}

            res1 = await agent.ainvoke((msg1),
                                config={"callbacks": [langfuse_handler]},
                                )
            print(res1)
            
if __name__ == "__main__":
    asyncio.run(main())
```
 **note : please add langfuse private key, secret key,host url and openai api key in environment.**

### SDK and container versions

os : Ubuntu

Python 3.10.12

Name: langfuse
Version: 3.4.0

Name: langgraph
Version: 0.4.3

Name: mcp
Version: 1.9.3

### Are you interested to contribute a fix for this bug?

Yes

**Comment by grimo8805** [comment]
hi @dosu, 
```

Traceback (most recent call last):
  File "/home/tarunkuk/demoo/new/client.py", line 31, in <module>
    langfuse_handler = CallbackHandler(
TypeError: LangchainCallbackHandler.__init__() got an unexpected keyword argument 'secret_key'
```
getting the  error

**Comment by grimo8805** [comment]
yes , i have added the keys to environment. and was able to get in the script.

still the below error.

[06/25/25 15:33:22] INFO     Processing request of type ListToolsRequest                                    server.py:558
Failed to export batch code: 404, reason: <!DOCTYPE html><html lang="en"><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><meta name="next-head-count" content="2"/><link rel="preload" href="/langfuse/_next/static/css/0a37468f281f4fde.css" as="style"/><link rel="stylesheet" href="/langfuse/_next/static/css/0a37468f281f4fde.css" data-n-g=""/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/langfuse/_next/static/chunks/polyfills-42372ed130431b0a.js"></script><script src="/langfuse/_next/static/chunks/webpack-5490f9c04512822f.js" defer=""></script><script src="/langfuse/_next/static/chunks/framework-d2dcb18632b956b2.js" defer=""></script><script src="/langfuse/_next/static/chunks/main-1b61adfb972c2a5d.js" defer=""></script><script src="/langfuse/_next/static/chunks/pages/_app-945871dd503b5be0.js" defer=""></script><script src="/langfuse/_next/static/chunks/pages/_error-a6b891bf0b43bbee.js" defer=""></script><script src="/langfuse/_next/static/ue3gGE60Ac4nvOrYmqPNY/_buildManifest.js" defer=""></script><script src="/langfuse/_next/static/ue3gGE60Ac4nvOrYmqPNY/_ssgManifest.js" defer=""></script></head><body><div id="__next"><script>!function(){try{var d=document.documentElement,c=d.classList;c.remove('light','dark');var e=localStorage.getItem('theme');if('system'===e||(!e&&true)){var t='(prefers-color-scheme: dark)',m=window.matchMedia(t);if(m.media!==t||m.matches){d.style.colorScheme = 'dark';c.add('dark')}else{d.style.colorScheme = 'light';c.add('light')}}else if(e){c.add(e|| '')}if(e==='light'||e==='dark')d.style.colorScheme=e}catch(e){}}()</script><div class="flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8" data-sentry-component="Spinner" data-sentry-source-file="spinner.tsx"><div class="sm:mx-auto sm:w-full sm:max-w-md"><img src="/langfuse/icon.svg" width="42" height="42" alt="Langfuse Icon" class="mx-auto motion-safe:animate-spin" data-sentry-component="LangfuseIcon" data-sentry-source-file="LangfuseLogo.tsx"/><h2 class="mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-primary">Loading ...</h2></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"ue3gGE60Ac4nvOrYmqPNY","assetPrefix":"/langfuse","nextExport":true,"isFallback":false,"gip":true,"locale":"en","locales":["en"],"defaultLocale":"en","scriptLoader":[]}</script></body></html>

**Comment by hassiebp** [comment]
@grimo8805 Thanks for raising this - it looks like something is off in your setup. Could you please share what you have configured as `LANGFUSE_HOST`?

**Comment by grimo8805** [comment]
```
services:
  langfuse-worker:
    image: langfuse/langfuse-worker:3
    restart: always
    depends_on: &langfuse-depends-on
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    ports:
      - "3030:3030"
    environment: &langfuse-worker-env
      DATABASE_URL:
      SALT: "mysalt"
      ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000" # generate via `openssl rand -hex 32`
      TELEMETRY_ENABLED: 'false'
      LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: 'true'
      CLICKHOUSE_MIGRATION_URL: 'clickhouse://clickhouse:9000'
      CLICKHOUSE_URL: 'http://clickhouse:8123'
      CLICKHOUSE_USER: 'CLICKHOUSE_USER'
      CLICKHOUSE_PASSWORD: 'CLICKHOUSE_PASSWORD'
      CLICKHOUSE_CLUSTER_ENABLED: 'false'
      LANGFUSE_S3_EVENT_UPLOAD_BUCKET: 'langfuse'
      LANGFUSE_S3_EVENT_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID: 'minio'
      LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY: 'miniosecret'
      LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT: 'http://xyz.com:9091'
      LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE: 'true'
      LANGFUSE_S3_EVENT_UPLOAD_PREFIX: 'events/'
      LANGFUSE_S3_MEDIA_UPLOAD_BUCKET: 'langfuse'
      LANGFUSE_S3_MEDIA_UPLOAD_REGION: 'auto'
      LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID: 'minio'
      LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY: 'miniosecret'
      LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT: 'http://xyz.com:9091'
      LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE: 'true'
      LANGFUSE_S3_MEDIA_UPLOAD_PREFIX: 'media/'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      REDIS_AUTH: 'myredissecret'
 
  langfuse-web:
    image: xyz-langfuse:3.4.0
    restart: always
    depends_on: *langfuse-depends-on
    ports:
      - "4000:3000"
    environment:
      <<: *langfuse-worker-env
      NEXTAUTH_SECRET: mysecret
      NEXT_PUBLIC_BASE_PATH: '/langfuse'
      NEXTAUTH_URL: https://xyz/langfuse/api/auth
#      LANGFUSE_INIT_ORG_ID: ${LANGFUSE_INIT_ORG_ID:-}
#      LANGFUSE_INIT_ORG_NAME: ${LANGFUSE_INIT_ORG_NAME:-}
#      LANGFUSE_INIT_PROJECT_ID: ${LANGFUSE_INIT_PROJECT_ID:-}
#      LANGFUSE_INIT_PROJECT_NAME: ${LANGFUSE_INIT_PROJECT_NAME:-}
#      LANGFUSE_INIT_PROJECT_PUBLIC_KEY: ${LANGFUSE_INIT_PROJECT_PUBLIC_KEY:-}
#      LANGFUSE_INIT_PROJECT_SECRET_KEY: ${LANGFUSE_INIT_PROJECT_SECRET_KEY:-}
#      LANGFUSE_INIT_USER_EMAIL: ${LANGFUSE_INIT_USER_EMAIL:-}
#      LANGFUSE_INIT_USER_NAME: ${LANGFUSE_INIT_USER_NAME:-}
#      LANGFUSE_INIT_USER_PASSWORD: ${LANGFUSE_INIT_USER_PASSWORD:-}
      LANGFUSE_SDK_CI_SYNC_PROCESSING_ENABLED: 'false'
      LANGFUSE_READ_FROM_POSTGRES_ONLY: 'false'
      LANGFUSE_READ_FROM_CLICKHOUSE_ONLY: 'true'
      LANGFUSE_RETURN_FROM_CLICKHOUSE: 'true'
 
  clickhouse:
    image: clickhouse/clickhouse-server
    restart: always
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: CLICKHOUSE_USER
      CLICKHOUSE_PASSWORD: CLICKHOUSE_PASSWORD
    volumes:
      - /opt/app2/langfuse/langfuse_clickhouse_data:/var/lib/clickhouse
      - /opt/app2/langfuse/langfuse_clickhouse_logs:/var/log/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 1s
 
  minio:
    image: minio/minio
    restart: always
    container_name: minio
    #hostname: minio
    entrypoint: sh
    # create the 'langfuse' bucket before starting the service
    command: -c 'mkdir -p /data/langfuse && minio server --address ":9091" --console-address ":9092" /data'
    environment:
      MINIO_ROOT_USER: MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: MINIO_ROOT_PASSWORD
    ports:
      - "9091:9091"
      - "9092:9092"
    volumes:
      - /opt/app2/langfuse/langfuse_minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 1s
 
  redis:
    image: redis:7
    restart: always
    command: >
      --requirepass ${REDIS_AUTH:-myredissecret}
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 10
 
  postgres:
    image: postgres:16.0
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10
    environment:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: usr
    ports:
      - 5432:5432
    volumes:
      - /opt/app2/langfuse/langfuse_postgres_data:/var/lib/postgresql/data
```


 hi @hassiebp , 
here is the yaml , we have used to configure over langfuse , on the server.
